/* Notícias para análise — recolhidas em 2026-09-28 a partir do Público e do Observador.
   Resumos feitos só a partir do título (o acesso direto aos sites estava bloqueado). */
window.ECO_NOTICIAS = [
  /* ---------- u1 — A atividade económica e a ciência económica ---------- */
  {
    u: 'u1',
    fonte: 'Observador',
    titulo: 'Livre acusa Governo de "falta de respeito institucional" por dizer que margem no OE é "muito limitada"',
    url: 'https://observador.pt/2026/09/26/livre-acusa-governo-de-falta-de-respeito-institucional-por-dizer-que-margem-no-oe-e-muito-limitada/',
    data: '2026-09-26',
    imagem: null,
    resumo: 'O Livre criticou o Governo por este ter afirmado que a margem no Orçamento do Estado é "muito limitada". A discussão acontece na preparação do Orçamento do Estado para 2027, em que os partidos apresentam as suas prioridades.',
    analise: 'Esta notícia é um exemplo claro do problema económico fundamental: os recursos (aqui, o dinheiro público) são escassos e as necessidades que os partidos querem satisfazer são ilimitadas. Dizer que a "margem é muito limitada" significa que o Estado, enquanto agente económico, tem de fazer escolhas. Cada euro gasto numa medida deixa de poder ser usado noutra — é o custo de oportunidade dessa decisão. Podes identificar as diferentes necessidades coletivas em disputa (saúde, pensões, habitação) e perceber que a economia estuda precisamente como afetar recursos escassos a usos alternativos. Pergunta para pensar: se o Governo decidir aumentar a despesa com pensões, qual poderá ser o custo de oportunidade dessa escolha?',
    conceitos: ['escassez', 'escolha', 'custo de oportunidade', 'necessidades coletivas'],
  },
  {
    u: 'u1',
    fonte: 'Público',
    titulo: 'Com as albufeiras cheias, sobe a pressão para expandir o regadio',
    url: 'https://www.publico.pt/2026/06/21/azul/noticia/albufeiras-cheias-sobe-pressao-expandir-regadio-2178501',
    data: '2026-06-21',
    imagem: null,
    resumo: 'Com as albufeiras cheias, aumenta a pressão para alargar as áreas de regadio. A água armazenada é um recurso disputado por vários usos, como a agricultura, o consumo humano e o turismo.',
    analise: 'A água é um recurso natural escasso, mesmo quando as albufeiras estão cheias: a quantidade é limitada e tem usos alternativos (agricultura, abastecimento das populações, indústria, turismo, ecossistemas). Expandir o regadio é uma escolha que tem um custo de oportunidade — a água usada nos campos deixa de estar disponível para outros fins, sobretudo em anos de seca. A notícia permite também distinguir os agentes económicos envolvidos (agricultores/empresas, famílias, Estado) e os seus interesses diferentes. Pergunta para pensar: porque é que a abundância de água num ano não elimina o problema da escassez a longo prazo?',
    conceitos: ['escassez', 'recursos naturais', 'usos alternativos', 'custo de oportunidade'],
  },
  {
    u: 'u1',
    fonte: 'Observador',
    titulo: 'Comissão Europeia alerta Estados-membros para impacto de verão seco e quente na agricultura',
    url: 'https://observador.pt/2026/09/02/comissao-europeia-alerta-estados-membros-para-impacto-de-verao-seco-e-quente-na-agricultura/',
    data: '2026-09-02',
    imagem: null,
    resumo: 'A Comissão Europeia avisou os Estados-membros sobre os efeitos de um verão seco e quente na agricultura. As condições climatéricas afetam a produção agrícola na União Europeia.',
    analise: 'Um verão seco reduz a disponibilidade de um recurso essencial (a água) e, por isso, torna mais evidente a escassez relativa: há menos recursos para produzir os bens que as pessoas desejam. Os agricultores terão de escolher o que produzir, onde regar e o que sacrificar — decisões com custo de oportunidade. Podes ainda ligar a notícia ao circuito económico: se a produção agrícola cair, as empresas vendem menos, os rendimentos dos agricultores descem e as famílias podem pagar mais pelos alimentos. Pergunta para pensar: que escolhas terá de fazer um agricultor com pouca água, e qual o custo de oportunidade de cada uma?',
    conceitos: ['escassez', 'escolha', 'agentes económicos', 'circuito económico'],
  },

  /* ---------- u2 — Necessidades e consumo ---------- */
  {
    u: 'u2',
    fonte: 'Observador',
    titulo: 'Cabaz alimentar desce 1,86 euros na última semana para 255,97 euros',
    url: 'https://observador.pt/2026/09/23/cabaz-alimentar-desce-186-euros-na-ultima-semana-para-25597-euros/',
    data: '2026-09-23',
    imagem: null,
    resumo: 'O preço do cabaz alimentar desceu 1,86 euros numa semana, fixando-se em 255,97 euros. O cabaz é um conjunto de bens alimentares essenciais cujo preço é acompanhado regularmente.',
    analise: 'O cabaz alimentar reúne bens que satisfazem necessidades primárias, cuja procura é pouco sensível às variações de preço. Segundo a lei de Engel, as famílias de rendimento mais baixo gastam uma percentagem maior do seu rendimento em alimentação, por isso são as mais afetadas quando o cabaz encarece — e as que mais beneficiam de uma descida. Podes analisar a estrutura do consumo (coeficiente orçamental da alimentação) e perceber porque é que uma pequena variação semanal importa pouco face à tendência de longo prazo. Pergunta para pensar: para uma família com baixo rendimento, qual o peso de 256 euros no orçamento mensal, comparado com uma família de rendimento elevado?',
    conceitos: ['lei de Engel', 'coeficiente orçamental', 'necessidades primárias', 'estrutura do consumo'],
  },
  {
    u: 'u2',
    fonte: 'Observador',
    titulo: 'Anacom multa NOS em 350 mil euros por alteração ilegal de contratos de 821 mil clientes para introduzir publicidade nas gravações de TV',
    url: 'https://observador.pt/2026/08/31/anacom-multa-nos-em-350-mil-euros-por-alteracao-ilegal-de-contratos-de-821-mil-clientes-para-introduzir-publicidade-nas-gravacoes-de-tv/',
    data: '2026-08-31',
    imagem: null,
    resumo: 'A Anacom aplicou à NOS uma multa de 350 mil euros por ter alterado ilegalmente os contratos de 821 mil clientes para introduzir publicidade nas gravações de televisão. A Anacom é o regulador das comunicações em Portugal.',
    analise: 'A notícia mostra os direitos do consumidor em ação: uma empresa não pode alterar unilateralmente as condições de um contrato, e existem entidades reguladoras que fiscalizam e punem essas práticas. Liga também ao tema da publicidade — a empresa quis inserir anúncios num serviço já pago, o que mostra como a publicidade é uma fonte de receita e pode influenciar os hábitos de consumo. Podes identificar o direito à informação e o direito à proteção dos interesses económicos do consumidor. Pergunta para pensar: que direitos do consumidor foram postos em causa e que papel tem o Estado (através dos reguladores) na sua defesa?',
    conceitos: ['direitos do consumidor', 'publicidade', 'entidades reguladoras'],
  },
  {
    u: 'u2',
    fonte: 'Público',
    titulo: 'França multa Shein por violações da legislação de defesa do consumidor',
    url: 'https://www.publico.pt/2026/06/03/impar/noticia/franca-multa-shein-violacoes-legislacao-defesa-consumidor-2177042',
    data: '2026-06-03',
    imagem: null,
    resumo: 'As autoridades francesas multaram a plataforma de moda Shein por violar a legislação de defesa do consumidor. A Shein é uma das maiores empresas de venda online de roupa a baixo preço.',
    analise: 'Este caso permite ligar três temas da unidade: direitos do consumidor, publicidade/práticas comerciais e consumo sustentável. Plataformas de "fast fashion" estimulam o consumismo com preços muito baixos e promoções constantes, o que pode levar a compras por impulso e a um grande desperdício de recursos. A multa mostra que o Estado intervém para proteger o consumidor de práticas enganosas. Podes contrapor o consumismo ao consumo responsável e sustentável (comprar menos, reutilizar, reparar). Pergunta para pensar: um preço muito baixo significa sempre uma boa compra para o consumidor e para a sociedade?',
    conceitos: ['direitos do consumidor', 'consumismo', 'consumo sustentável', 'publicidade'],
  },

  /* ---------- u3 — A produção de bens e serviços ---------- */
  {
    u: 'u3',
    fonte: 'Público',
    titulo: 'Imigrantes e formação são chave para resolver escassez de mão-de-obra, diz relatório',
    url: 'https://www.publico.pt/2026/05/26/economia/noticia/imigrantes-formacao-sao-chave-resolver-escassez-maodeobra-conclui-relatorio-2176080',
    data: '2026-05-26',
    imagem: null,
    resumo: 'Um relatório conclui que os imigrantes e a formação são essenciais para resolver a falta de mão-de-obra em Portugal. A escassez de trabalhadores afeta vários setores da economia.',
    analise: 'O trabalho é um fator de produção, e esta notícia mostra que a sua quantidade (população ativa) e a sua qualidade (qualificação, capital humano) condicionam a capacidade de produzir. A imigração aumenta a quantidade de fator trabalho disponível; a formação aumenta a produtividade do trabalho. Podes relacionar com o envelhecimento da população e com a diferença entre população ativa, empregada e desempregada. Pergunta para pensar: porque é que investir em formação pode ter um efeito mais duradouro na produção do que apenas aumentar o número de trabalhadores?',
    conceitos: ['fator trabalho', 'população ativa', 'capital humano', 'produtividade'],
  },
  {
    u: 'u3',
    fonte: 'Observador',
    titulo: 'INE. Taxa de desemprego desce para 5,3% no 2.º trimestre',
    url: 'https://observador.pt/2026/08/05/ine-taxa-de-desemprego-desce-para-53-no-2-o-trimestre/',
    data: '2026-08-05',
    imagem: null,
    resumo: 'Segundo o INE, a taxa de desemprego desceu para 5,3% no segundo trimestre de 2026. O INE calcula esta taxa a partir do Inquérito ao Emprego.',
    analise: 'A taxa de desemprego calcula-se dividindo a população desempregada pela população ativa (empregados + desempregados) e multiplicando por 100. Uma descida pode resultar de mais emprego, mas também de alterações na população ativa — por isso convém analisar os dois lados da fração. Podes ainda distinguir tipos de desemprego (friccional, estrutural, conjuntural/cíclico) e ligar a descida ao crescimento da produção. Pergunta para pensar: se a população ativa aumentar muito por causa da imigração, a taxa de desemprego pode descer mesmo que o número de desempregados se mantenha? Porquê?',
    conceitos: ['taxa de desemprego', 'população ativa', 'tipos de desemprego'],
  },
  {
    u: 'u3',
    fonte: 'Observador',
    titulo: 'Tekever capta mais 500 milhões passando a valer mais de 5,5 mil milhões de euros',
    url: 'https://observador.pt/2026/09/23/tekever-capta-mais-500-milhoes-passando-a-valer-mais-de-55-mil-milhoes-de-euros/',
    data: '2026-09-23',
    imagem: null,
    resumo: 'A empresa portuguesa Tekever angariou mais 500 milhões de euros de investidores. Com esta operação, a empresa passa a ser avaliada em mais de 5,5 mil milhões de euros.',
    analise: 'Para produzir, as empresas precisam de combinar fatores de produção — recursos naturais, trabalho e capital — e o financiamento angariado permite adquirir capital técnico (equipamentos, tecnologia) e contratar trabalhadores qualificados. Esta notícia ilustra o investimento como aquisição de capital produtivo que aumenta a capacidade de produção futura, e a importância da inovação tecnológica na produtividade. Podes também refletir sobre como o valor acrescentado de uma empresa tecnológica tende a ser elevado. Pergunta para pensar: em que tipo de investimento (material ou imaterial) achas que uma empresa tecnológica vai aplicar a maior parte destes 500 milhões?',
    conceitos: ['fatores de produção', 'investimento', 'inovação', 'valor acrescentado'],
  },

  /* ---------- u4 — Comércio e moeda ---------- */
  {
    u: 'u4',
    fonte: 'Público',
    titulo: 'Em 2027, será possível pagar com MB Way em lojas de Espanha, França ou Itália',
    url: 'https://www.publico.pt/2026/04/16/economia/noticia/proximo-ano-sera-possivel-pagar-mb-way-lojas-espanha-franca-italia-2171478',
    data: '2026-04-16',
    imagem: null,
    resumo: 'A partir de 2027, os utilizadores do MB Way poderão pagar em lojas de Espanha, França e Itália. O MB Way é uma aplicação portuguesa de pagamentos eletrónicos.',
    analise: 'O MB Way é um exemplo de moeda escritural e de meios de pagamento eletrónicos: não se trocam notas, mas sim saldos de contas bancárias. A notícia mostra a evolução das formas de moeda (da moeda metálica à moeda-papel, à moeda escritural e aos pagamentos digitais) e como a interligação entre países europeus facilita as trocas na zona euro. Podes relacionar com as funções da moeda, sobretudo a de meio de pagamento (intermediário nas trocas). Pergunta para pensar: que vantagens e riscos tem para um consumidor pagar com o telemóvel em vez de usar numerário?',
    conceitos: ['meios de pagamento', 'moeda escritural', 'pagamentos eletrónicos', 'funções da moeda'],
  },
  {
    u: 'u4',
    fonte: 'Observador',
    titulo: 'BCE. Euro digital pode acabar com dependência da UE',
    url: 'https://observador.pt/2026/06/15/euro-digital-e-uma-oportunidade-para-acabar-com-as-dependencias-da-ue/',
    data: '2026-06-15',
    imagem: null,
    resumo: 'O Banco Central Europeu defende que o euro digital pode acabar com dependências da União Europeia. O euro digital é um projeto do BCE para criar uma forma digital de moeda emitida pelo banco central.',
    analise: 'O euro digital seria moeda emitida diretamente pelo banco central, tal como as notas, mas em formato digital — diferente do dinheiro que temos no banco (moeda escritural, criada pelos bancos comerciais). A "dependência" referida está ligada ao facto de muitos pagamentos com cartão na Europa passarem por empresas não europeias. Podes analisar as funções da moeda (meio de pagamento, unidade de conta, reserva de valor) e perguntar se o euro digital as cumpre todas. Pergunta para pensar: qual a diferença entre ter 100 euros em euro digital e ter 100 euros numa conta à ordem num banco comercial?',
    conceitos: ['euro digital', 'banco central', 'funções da moeda', 'meios de pagamento'],
  },
  {
    u: 'u4',
    fonte: 'Observador',
    titulo: 'CTT baixam lucros no semestre que teve desafio acrescido com a taxa europeia para encomendas abaixo de 150 euros',
    url: 'https://observador.pt/2026/07/28/ctt-baixam-lucros-no-semestre-que-teve-desafio-acrescido-com-a-taxa-europeia-para-encomendas-abaixo-de-150-euros/',
    data: '2026-07-28',
    imagem: null,
    resumo: 'Os CTT registaram uma descida dos lucros no semestre. O período ficou marcado pela nova taxa europeia aplicada às encomendas de valor inferior a 150 euros que entram na União Europeia.',
    analise: 'A notícia liga o comércio eletrónico aos circuitos de distribuição: as encomendas compradas online a plataformas de fora da UE têm de ser transportadas e entregues, e os CTT são um dos intermediários desse circuito. Uma taxa sobre encomendas de baixo valor encarece o comércio eletrónico internacional e pode reduzir o volume de encomendas, afetando as empresas de logística. Podes distinguir circuito curto/longo e comércio tradicional/eletrónico, e pensar em quem suporta o custo da taxa. Pergunta para pensar: se a taxa reduzir as compras em plataformas estrangeiras, que tipo de comércio poderá beneficiar?',
    conceitos: ['comércio eletrónico', 'circuitos de distribuição', 'intermediários'],
  },

  /* ---------- u5 — Preços e mercados ---------- */
  {
    u: 'u5',
    fonte: 'Observador',
    titulo: 'Preços das casas abrandam para subida de 16,5% no segundo trimestre, com menos 6,4% de transações',
    url: 'https://observador.pt/2026/09/22/precos-das-casas-abrandam-para-subida-de-165-no-segundo-trimestre-com-menos-64-de-transacoes/',
    data: '2026-09-22',
    imagem: null,
    resumo: 'Os preços das casas subiram 16,5% no segundo trimestre, um ritmo mais lento do que antes. O número de transações de habitações caiu 6,4%.',
    analise: 'Esta notícia é ideal para aplicar o modelo da procura e da oferta. Preços muito altos fazem diminuir a quantidade procurada (menos transações), e fatores como a subida das taxas de juro podem deslocar a curva da procura para a esquerda. Atenção: "abrandar" não significa que os preços desceram — continuam a subir, mas a um ritmo menor. Podes discutir porque é que a oferta de habitação é pouco elástica a curto prazo (construir demora anos). Pergunta para pensar: que fatores poderão ter deslocado a curva da procura de habitação e o que aconteceria ao preço se a oferta aumentasse?',
    conceitos: ['procura e oferta', 'deslocação da curva da procura', 'elasticidade da oferta', 'preço de equilíbrio'],
  },
  {
    u: 'u5',
    fonte: 'Observador',
    titulo: 'INE confirma que taxa de inflação acelerou para 3,3% em agosto. Rendas podem subir até 2,56% em 2027',
    url: 'https://observador.pt/2026/09/10/ine-confirma-que-taxa-de-inflacao-acelerou-para-33-em-agosto/',
    data: '2026-09-10',
    imagem: null,
    resumo: 'O INE confirmou que a taxa de inflação acelerou para 3,3% em agosto. Com base nestes dados, as rendas poderão subir até 2,56% em 2027.',
    analise: 'A inflação mede-se pela taxa de variação do Índice de Preços no Consumidor (IPC), que o INE calcula a partir de um cabaz representativo do consumo das famílias. "Acelerar" significa que os preços sobem mais depressa do que antes. A notícia mostra também um efeito prático: a atualização das rendas está ligada à inflação. Podes relacionar com a perda de poder de compra quando os rendimentos sobem menos do que os preços e distinguir inflação de procura e inflação de custos. Pergunta para pensar: se o teu salário subir 2% num ano em que a inflação é de 3,3%, o teu poder de compra aumentou ou diminuiu?',
    conceitos: ['inflação', 'IPC', 'poder de compra'],
  },
  {
    u: 'u5',
    fonte: 'Público',
    titulo: 'Preço dos combustíveis deve subir entre oito e dez cêntimos na próxima semana',
    url: 'https://publico.pt/2026/08/14/economia/noticia/preco-combustiveis-subir-oito-dez-centimos-proxima-semana-2185046',
    data: '2026-08-14',
    imagem: null,
    resumo: 'O preço dos combustíveis deverá subir entre oito e dez cêntimos por litro na semana seguinte. Os preços dos combustíveis em Portugal são revistos semanalmente.',
    analise: 'Os combustíveis são um bom exemplo de bem com procura pouco elástica (rígida): mesmo com subidas de preço, as pessoas continuam a precisar de se deslocar, pelo que a quantidade procurada varia pouco. A subida resulta sobretudo de fatores do lado da oferta, como o preço do petróleo, que deslocam a curva da oferta para a esquerda. Podes também discutir a estrutura de mercado (poucas empresas petrolíferas — oligopólio) e o impacto dos combustíveis na inflação, porque encarecem o transporte de quase todos os bens. Pergunta para pensar: porque é que uma subida do preço dos combustíveis pode fazer subir o preço de bens que nada têm a ver com petróleo?',
    conceitos: ['elasticidade-preço da procura', 'oferta', 'oligopólio', 'inflação de custos'],
  },

  /* ---------- u6 — Rendimentos e repartição dos rendimentos ---------- */
  {
    u: 'u6',
    fonte: 'Observador',
    titulo: 'Com OE à vista, Concertação Social dividiu-se no salário mínimo. Sindicatos pedem "choque salarial", patrões fecham porta à revisão',
    url: 'https://observador.pt/2026/09/16/com-oe-a-vista-concertacao-social-dividiu-se-no-salario-minimo-sindicatos-pedem-choque-salarial-patroes-fecham-porta-a-revisao/',
    data: '2026-09-16',
    imagem: null,
    resumo: 'Na Concertação Social, sindicatos e patrões dividiram-se quanto ao salário mínimo. Os sindicatos pedem um "choque salarial" e as confederações patronais recusam rever o valor já acordado.',
    analise: 'O salário é a remuneração do fator trabalho e o salário mínimo é um instrumento de repartição dos rendimentos fixado pelo Estado com os parceiros sociais. Os sindicatos defendem que um aumento melhora o salário real e reduz a desigualdade; os patrões argumentam com os custos de produção e a produtividade. Podes analisar a repartição funcional (entre trabalho e capital) e o papel da Concertação Social. Pergunta para pensar: um aumento do salário mínimo aumenta sempre o poder de compra dos trabalhadores? De que depende?',
    conceitos: ['salário mínimo', 'salário real', 'repartição funcional', 'concertação social'],
  },
  {
    u: 'u6',
    fonte: 'Observador',
    titulo: 'Remuneração bruta total mensal dos trabalhadores cresce 1,8% no 2.º trimestre',
    url: 'https://observador.pt/2026/08/14/remuneracao-bruta-total-mensal-dos-trabalhadores-cresce-18-no-2-o-trimestre/',
    data: '2026-08-14',
    imagem: null,
    resumo: 'A remuneração bruta total mensal dos trabalhadores cresceu 1,8% no segundo trimestre. O INE publica regularmente dados sobre a evolução das remunerações.',
    analise: 'A notícia é ótima para treinar a diferença entre salário nominal e salário real, e entre remuneração bruta e líquida. A remuneração bruta é antes dos descontos (IRS e contribuições para a Segurança Social); a líquida é o que o trabalhador recebe. Para saber se o poder de compra aumentou, compara-se a variação dos salários com a taxa de inflação: salário real ≈ variação nominal − inflação. Quando lês estas notícias, verifica sempre se o número apresentado é nominal ou real. Pergunta para pensar: se esta variação fosse nominal e a inflação estivesse acima de 3%, o que teria acontecido ao salário real?',
    conceitos: ['salário nominal', 'salário real', 'remuneração bruta e líquida', 'poder de compra'],
  },
  {
    u: 'u6',
    fonte: 'Público',
    titulo: 'FMI: IRS Jovem e IVA reduzido na restauração devem ser revertidos',
    url: 'https://www.publico.pt/2026/05/06/economia/noticia/fmi-irs-jovem-iva-reduzido-restauracao-revertidos-2173800',
    data: '2026-05-06',
    imagem: null,
    resumo: 'O FMI defende que o IRS Jovem e o IVA reduzido na restauração devem ser revertidos. O IRS Jovem é um regime que reduz o imposto sobre o rendimento dos trabalhadores mais novos.',
    analise: 'O IRS é um imposto direto e progressivo, um dos principais instrumentos de redistribuição dos rendimentos: quem ganha mais paga uma taxa maior. O IRS Jovem cria um tratamento mais favorável para um grupo, o que levanta questões de equidade (dois trabalhadores com o mesmo salário pagam impostos diferentes consoante a idade). O IVA, pelo contrário, é um imposto indireto que tende a ser regressivo. Podes distinguir rendimento primário e rendimento disponível e analisar como os impostos alteram a repartição. Pergunta para pensar: o IRS Jovem torna a repartição dos rendimentos mais justa ou menos justa? Apresenta um argumento a favor e outro contra.',
    conceitos: ['IRS', 'redistribuição', 'impostos diretos e indiretos', 'rendimento disponível'],
  },

  /* ---------- u7 — Utilização dos rendimentos ---------- */
  {
    u: 'u7',
    fonte: 'Público',
    titulo: 'Euribor acima de 3% agrava crédito à habitação a taxa variável',
    url: 'https://www.publico.pt/2026/09/23/economia/noticia/euribor-acima-3-agrava-credito-habitacao-taxa-variavel-2189014',
    data: '2026-09-23',
    imagem: null,
    resumo: 'A Euribor ultrapassou os 3%, o que torna mais caros os créditos à habitação com taxa variável. A Euribor é a taxa de referência usada no cálculo dos juros de grande parte dos empréstimos para compra de casa.',
    analise: 'A taxa de juro é o preço do dinheiro: para quem pede emprestado é um custo, para quem poupa é uma remuneração. No crédito a taxa variável, a taxa paga = Euribor + spread, por isso uma subida da Euribor aumenta a prestação mensal e reduz o rendimento disponível para consumo e poupança. Podes comparar taxa fixa e taxa variável (quem suporta o risco) e relacionar com as decisões do BCE. Pergunta para pensar: se tivesses de contratar hoje um crédito à habitação, escolherias taxa fixa ou variável? Justifica com o conceito de risco.',
    conceitos: ['taxa de juro', 'crédito à habitação', 'Euribor', 'rendimento disponível'],
  },
  {
    u: 'u7',
    fonte: 'Público',
    titulo: 'Taxa de juro e novo limite aceleram crescimento dos Certificados de Aforro',
    url: 'https://www.publico.pt/2026/06/19/economia/noticia/taxa-juro-novo-limite-aceleram-crescimento-certificados-aforro-2178804',
    data: '2026-06-19',
    imagem: null,
    resumo: 'Os Certificados de Aforro estão a crescer mais depressa, graças à taxa de juro e a um novo limite de subscrição. Os Certificados de Aforro são um produto de poupança emitido pelo Estado português.',
    analise: 'A notícia mostra como a taxa de juro influencia as decisões de aplicação da poupança: quando um produto paga mais juros, torna-se mais atrativo face a alternativas como os depósitos a prazo. Os Certificados de Aforro são uma aplicação financeira de baixo risco e, ao comprá-los, as famílias estão a emprestar dinheiro ao Estado — ajudam a financiar a dívida pública. Podes comparar rendibilidade, risco e liquidez de diferentes aplicações (depósitos, certificados, ações, obrigações). Pergunta para pensar: porque é que uma família prudente pode preferir Certificados de Aforro a ações, mesmo que estas possam render mais?',
    conceitos: ['poupança', 'aplicações financeiras', 'rendibilidade e risco', 'taxa de juro'],
  },
  {
    u: 'u7',
    fonte: 'Observador',
    titulo: 'Novo regulamento de bolsas aplicado de forma faseada em 2026-2027',
    url: 'https://observador.pt/2026/08/11/novo-regulamento-de-bolsas-aplicado-de-forma-faseada-em-2026-2027/',
    data: '2026-08-11',
    imagem: null,
    resumo: 'Um novo regulamento de bolsas vai ser aplicado de forma faseada entre 2026 e 2027. As bolsas são mercados onde se compram e vendem valores mobiliários, como ações e obrigações.',
    analise: 'A bolsa de valores é o mercado de títulos onde se transacionam ações (partes do capital de uma empresa, que dão direito a dividendos) e obrigações (títulos de dívida, que dão direito a juros). Estas regras ajudam a proteger quem aplica a sua poupança e a garantir transparência. Podes relacionar com o mercado primário (emissão de novos títulos, que financia as empresas) e secundário (compra e venda de títulos já existentes). Pergunta para pensar: qual a diferença, para um aforrador, entre comprar uma ação e comprar uma obrigação da mesma empresa?',
    conceitos: ['bolsa de valores', 'ações', 'obrigações', 'mercado de títulos'],
  },

  /* ---------- u8 — A contabilidade nacional ---------- */
  {
    u: 'u8',
    fonte: 'Observador',
    titulo: 'Economia portuguesa cresceu 0,8% no segundo trimestre em cima de subida de 0,1% no primeiro. Crescimento homólogo foi de 2,5%',
    url: 'https://observador.pt/2026/07/30/economia-portuguesa-cresceu-08-no-segundo-trimestre-em-cima-de-subida-de-01-no-primeiro-crescimento-homologo-foi-de-25/',
    data: '2026-07-30',
    imagem: null,
    resumo: 'A economia portuguesa cresceu 0,8% no segundo trimestre, depois de uma subida de 0,1% no primeiro. Face ao mesmo trimestre do ano anterior, o crescimento foi de 2,5%.',
    analise: 'Esta notícia obriga a distinguir duas formas de medir o crescimento do PIB: a variação em cadeia (face ao trimestre anterior: 0,8%) e a variação homóloga (face ao mesmo trimestre do ano anterior: 2,5%). O PIB mede o valor dos bens e serviços finais produzidos no país e pode ser calculado pelas óticas da produção, do rendimento e da despesa (C + I + G + X − M). Convém saber que estes valores são em volume (PIB real), ou seja, descontam o efeito dos preços. Pergunta para pensar: porque é que o INE publica as duas taxas, e qual delas é mais útil para perceber se a economia está a acelerar agora?',
    conceitos: ['PIB', 'variação em cadeia', 'variação homóloga', 'ótica da despesa'],
  },
  {
    u: 'u8',
    fonte: 'Observador',
    titulo: 'Só se "muita coisa correr mal" Portugal cresce menos de 2% em 2026, diz Fórum para a Competitividade',
    url: 'https://observador.pt/2026/09/04/so-se-muita-coisa-correr-mal-portugal-cresce-menos-de-2-em-2026-diz-forum-para-a-competitividade/',
    data: '2026-09-04',
    imagem: null,
    resumo: 'O Fórum para a Competitividade considera que Portugal só crescerá menos de 2% em 2026 se "muita coisa correr mal". A previsão refere-se ao crescimento do PIB no ano.',
    analise: 'As previsões de crescimento do PIB são estimativas feitas por várias instituições (Banco de Portugal, Governo, Comissão Europeia, associações) e servem de base a decisões como o Orçamento do Estado. Podes analisar a taxa de crescimento real do PIB como indicador do crescimento económico e lembrar os seus limites: não mede a repartição dos rendimentos, a economia informal nem o bem-estar. Compara esta previsão com as de outras instituições para perceber porque divergem. Pergunta para pensar: se o PIB crescer 2% e a população também aumentar, o que acontece ao PIB per capita?',
    conceitos: ['crescimento económico', 'PIB real', 'PIB per capita', 'previsões económicas'],
  },
  {
    u: 'u8',
    fonte: 'Público',
    titulo: 'Banco de Portugal prevê crescimento abaixo de 2% e regresso a défice este ano',
    url: 'https://www.publico.pt/2026/06/15/economia/noticia/banco-portugal-preve-crescimento-abaixo-2-regresso-defice-ano-2178220',
    data: '2026-06-15',
    imagem: null,
    resumo: 'O Banco de Portugal prevê que a economia cresça menos de 2% este ano e que as contas públicas regressem a um défice. O Banco de Portugal publica regularmente projeções para a economia portuguesa.',
    analise: 'Esta notícia liga a contabilidade nacional às finanças públicas: o saldo orçamental costuma ser apresentado em percentagem do PIB, por isso o crescimento da economia influencia diretamente o défice. Um crescimento mais fraco significa, em regra, menos receita fiscal e mais despesa social. Podes comparar esta previsão com a do Fórum para a Competitividade (u8) e com os dados efetivos do INE, percebendo a diferença entre previsões e contas nacionais já apuradas. Pergunta para pensar: porque é que instituições diferentes chegam a previsões diferentes para o mesmo PIB?',
    conceitos: ['previsões do PIB', 'Banco de Portugal', 'crescimento económico', 'saldo orçamental em % do PIB'],
  },

  /* ---------- u9 — As relações económicas com o resto do mundo ---------- */
  {
    u: 'u9',
    fonte: 'Observador',
    titulo: 'Exportações sobem 2,5% e importações 5,5% até julho',
    url: 'https://observador.pt/2026/09/09/exportacoes-sobem-25-e-importacoes-55-ate-julho/',
    data: '2026-09-09',
    imagem: null,
    resumo: 'Até julho, as exportações subiram 2,5% e as importações 5,5%. Os dados sobre o comércio internacional de bens são publicados pelo INE.',
    analise: 'Quando as importações crescem mais depressa do que as exportações, o saldo da balança de bens tende a agravar-se (maior défice comercial) e a taxa de cobertura (exportações/importações × 100) diminui. Podes relacionar com a procura interna (mais consumo e investimento geram mais importações) e com a competitividade das empresas exportadoras. Lembra-te que a balança de bens é apenas uma parte da balança corrente, que inclui também os serviços, como o turismo. Pergunta para pensar: se as exportações sobem 2,5% e as importações 5,5%, a taxa de cobertura aumenta ou diminui? Porquê?',
    conceitos: ['exportações', 'importações', 'saldo da balança de bens', 'taxa de cobertura'],
  },
  {
    u: 'u9',
    fonte: 'Observador',
    titulo: 'Economia portuguesa acumula excedente externo de 1.201 milhões até junho, estima Banco de Portugal',
    url: 'https://observador.pt/2026/08/19/economia-portuguesa-acumula-excedente-externo-de-1-201-milhoes-ate-junho-estima-banco-de-portugal/',
    data: '2026-08-19',
    imagem: null,
    resumo: 'Segundo o Banco de Portugal, a economia portuguesa acumulou um excedente externo de 1.201 milhões de euros até junho. O Banco de Portugal é responsável pelas estatísticas da balança de pagamentos.',
    analise: 'O "excedente externo" refere-se ao saldo conjunto da balança corrente e de capital: significa que Portugal recebeu do resto do mundo mais do que pagou, tendo capacidade de financiamento face ao exterior. Compara com a notícia das exportações e importações de bens: mesmo com défice na balança de bens, o país pode ter excedente graças ao saldo positivo dos serviços (sobretudo turismo) e às transferências de fundos europeus (balança de capital). Pergunta para pensar: como é possível Portugal ter défice na balança de bens e, ao mesmo tempo, excedente externo?',
    conceitos: ['balança corrente', 'balança de capital', 'capacidade de financiamento', 'balança de pagamentos'],
  },
  {
    u: 'u9',
    fonte: 'Público',
    titulo: 'Receitas do turismo acentuam abrandamento no semestre',
    url: 'https://publico.pt/2026/08/30/economia/noticia/receitas-turismo-acentuam-abrandamento-semestre-2186474',
    data: '2026-08-30',
    imagem: null,
    resumo: 'As receitas do turismo abrandaram de forma mais acentuada no semestre. O turismo é uma das principais fontes de receita externa da economia portuguesa.',
    analise: 'As despesas de turistas estrangeiros em Portugal são exportações de serviços e entram na balança de serviços (rubrica "viagens e turismo"), que costuma ser muito positiva e compensa parte do défice da balança de bens. "Abrandar" não significa cair: as receitas continuam a crescer, mas mais devagar. Podes analisar a dependência da economia portuguesa do turismo e os riscos de especialização num único setor. Pergunta para pensar: se as receitas do turismo abrandarem muito, que efeito isso pode ter no saldo da balança corrente?',
    conceitos: ['exportação de serviços', 'balança de serviços', 'turismo', 'balança corrente'],
  },

  /* ---------- u10 — A intervenção do Estado na economia ---------- */
  {
    u: 'u10',
    fonte: 'Observador',
    titulo: 'Orçamento do Estado para 2027 já tem pressão adicional de 4.783 milhões de euros. IVA e IRS do pacote para a habitação custam 303 milhões',
    url: 'https://observador.pt/2026/09/01/orcamento-do-estado-para-2027-ja-tem-pressao-de-4-783-milhoes-de-euros-iva-e-irs-do-pacote-para-a-habitacao-custam-303-milhoes/',
    data: '2026-09-01',
    imagem: null,
    resumo: 'O Orçamento do Estado para 2027 já tem uma pressão adicional de 4.783 milhões de euros resultante de medidas já decididas. As alterações ao IVA e ao IRS incluídas no pacote para a habitação custam 303 milhões.',
    analise: 'O Orçamento do Estado é o documento que prevê as receitas e as despesas públicas para um ano. Aqui, "pressão" significa despesa já comprometida ou receita perdida antes de o orçamento ser feito, o que reduz a margem para novas medidas. As descidas de IVA e IRS na habitação são despesa fiscal: o Estado abdica de receita para incentivar um comportamento (construir/arrendar). Podes analisar as funções do Estado (afetação, redistribuição, estabilização) e o impacto no saldo orçamental. Pergunta para pensar: porque é que uma descida de impostos tem, para o saldo orçamental, um efeito semelhante a um aumento de despesa?',
    conceitos: ['Orçamento do Estado', 'receitas e despesas públicas', 'saldo orçamental', 'política orçamental'],
  },
  {
    u: 'u10',
    fonte: 'Observador',
    titulo: 'Excedente orçamental fica nos 0,5% no primeiro semestre',
    url: 'https://observador.pt/2026/09/23/excedente-orcamental-fica-nos-05-no-primeiro-semestre-do-ano/',
    data: '2026-09-23',
    imagem: null,
    resumo: 'As contas públicas registaram um excedente orçamental de 0,5% no primeiro semestre. O saldo orçamental é a diferença entre receitas e despesas das Administrações Públicas.',
    analise: 'Há excedente orçamental quando as receitas públicas são superiores às despesas; há défice no caso contrário. O valor é apresentado em percentagem do PIB, o que permite comparar países e anos. Um excedente permite reduzir a dívida pública, mas também pode significar que o Estado está a cobrar mais ou a investir menos. Podes relacionar com as regras orçamentais europeias e com a política orçamental (expansionista ou restritiva). Pergunta para pensar: um excedente no primeiro semestre garante um excedente no ano inteiro? Que fatores podem mudar o resultado?',
    conceitos: ['saldo orçamental', 'excedente', 'dívida pública', 'política orçamental'],
  },
  {
    u: 'u10',
    fonte: 'Público',
    titulo: 'BCE mantém as taxas de juro em 2,25%',
    url: 'https://www.publico.pt/2026/07/23/economia/noticia/bce-mantem-taxas-juro-225-2182777',
    data: '2026-07-23',
    imagem: null,
    resumo: 'O Banco Central Europeu decidiu manter as taxas de juro diretoras em 2,25%. O BCE define a política monetária para todos os países da zona euro.',
    analise: 'A política monetária da zona euro é definida pelo BCE, e não pelo Governo português: é um exemplo de como parte da intervenção económica foi transferida para a União Europeia. O principal objetivo do BCE é a estabilidade dos preços (inflação próxima de 2%). Subir as taxas de juro encarece o crédito e trava a procura e a inflação; baixá-las estimula o consumo e o investimento. Manter as taxas é uma decisão de "esperar para ver". Pergunta para pensar: com a inflação em Portugal acima de 3% em agosto, que decisão esperarias do BCE nas reuniões seguintes? Porquê?',
    conceitos: ['política monetária', 'BCE', 'taxas de juro diretoras', 'estabilidade dos preços'],
  },

  /* ---------- u11 — A economia portuguesa no contexto da União Europeia ---------- */
  {
    u: 'u11',
    fonte: 'Observador',
    titulo: '"O PRR está totalmente concluído" com contratualização acima de 100%. Só em setembro se saberá quanto terá de ir para Orçamento',
    url: 'https://observador.pt/2026/08/28/o-prr-esta-totalmente-concluido-garante-castro-almeida/',
    data: '2026-08-28',
    imagem: null,
    resumo: 'O Governo afirma que o Plano de Recuperação e Resiliência (PRR) está totalmente concluído, com contratualização acima de 100%. Só em setembro se saberá quanto terá de ser financiado pelo Orçamento do Estado.',
    analise: 'O PRR é o plano português financiado pelo instrumento europeu NextGenerationEU, criado após a pandemia, e é um exemplo concreto de solidariedade financeira na União Europeia. Os fundos são entregues mediante o cumprimento de marcos e metas; o que não for pago pela UE pode ter de ser suportado pelo Orçamento do Estado. Podes analisar o impacto destes fundos no investimento público, no PIB e na balança de capital. Pergunta para pensar: porque é que o fim do PRR pode levar a um abrandamento do investimento em Portugal?',
    conceitos: ['PRR', 'fundos europeus', 'investimento público', 'NextGenerationEU'],
  },
  {
    u: 'u11',
    fonte: 'Observador',
    titulo: 'Portugal e 15 países da UE exigem que novo orçamento plurianual não corte na coesão nem na agricultura',
    url: 'https://observador.pt/2026/06/18/portugal-e-15-paises-da-ue-exigem-que-novo-orcamento-plurianual-nao-corte-na-coesao-nem-na-agricultura/',
    data: '2026-06-18',
    imagem: null,
    resumo: 'Portugal e outros 15 países da UE exigem que o próximo orçamento plurianual da União não corte nas verbas da coesão nem da agricultura. O orçamento plurianual define as despesas da UE para vários anos.',
    analise: 'O Quadro Financeiro Plurianual é o orçamento de longo prazo da UE. A política de coesão procura reduzir as disparidades de desenvolvimento entre regiões, e a Política Agrícola Comum (PAC) apoia os agricultores e o desenvolvimento rural — Portugal é um grande beneficiário de ambas. A notícia mostra que os Estados-membros negociam em grupos com interesses comuns ("Amigos da Coesão") face a países contribuintes líquidos. Pergunta para pensar: porque é que os países mais ricos da UE aceitam financiar a coesão de países como Portugal? Que benefícios obtêm?',
    conceitos: ['política de coesão', 'PAC', 'orçamento da UE', 'contribuinte líquido'],
  },
  {
    u: 'u11',
    fonte: 'Público',
    titulo: 'Fundos estruturais: Portugal reafectou 2,5 mil milhões de euros para as novas prioridades da UE',
    url: 'https://www.publico.pt/2026/03/25/economia/noticia/fundos-estruturais-portugal-reafectou-25-mil-milhoes-euros-novas-prioridades-ue-2169098',
    data: '2026-03-25',
    imagem: null,
    resumo: 'Portugal reafetou 2,5 mil milhões de euros de fundos estruturais para as novas prioridades da União Europeia. Os fundos estruturais financiam projetos de desenvolvimento nos Estados-membros.',
    analise: 'Os fundos estruturais (como o FEDER e o FSE+) fazem parte da política de coesão e são geridos em Portugal através do programa Portugal 2030. Reafetar fundos significa mudar a sua finalidade, o que implica escolhas: ao financiar as novas prioridades europeias, deixa-se de financiar outros projetos — há um custo de oportunidade. Podes ligar a notícia à forma como as prioridades da UE (transição verde, digital, defesa, competitividade) moldam o investimento nacional. Pergunta para pensar: que vantagens e desvantagens tem para Portugal adaptar o uso dos fundos às prioridades definidas em Bruxelas?',
    conceitos: ['fundos estruturais', 'política de coesão', 'Portugal 2030', 'prioridades da UE'],
  },
];
