/* Perguntas de escolha múltipla — Economia A, unidade 8 */
(window.ECO_PERGUNTAS = window.ECO_PERGUNTAS || []).push(
  { id: 'u8-01', u: 'u8',
    p: 'A função principal do setor institucional das sociedades não financeiras é',
    o: ['produzir bens e serviços mercantis não financeiros.',
        'captar poupanças e conceder crédito aos outros agentes.',
        'produzir serviços não mercantis e redistribuir o rendimento.',
        'consumir bens e serviços para satisfazer necessidades.'],
    c: 0,
    e: 'As sociedades não financeiras são as empresas que produzem bens e serviços destinados à venda no mercado, e o seu recurso principal são as receitas das vendas. Captar poupanças e conceder crédito é a função das sociedades financeiras, e redistribuir o rendimento cabe às administrações públicas.' },

  { id: 'u8-02', u: 'u8',
    p: 'O senhor Joaquim é dono de uma mercearia em Viseu, que explora em nome individual, sem ter constituído qualquer sociedade. Na contabilidade nacional, esta unidade produtiva é incluída no setor',
    o: ['das sociedades não financeiras.',
        'das famílias.',
        'das instituições sem fim lucrativo ao serviço das famílias.',
        'das sociedades financeiras.'],
    c: 1,
    e: 'Os empresários em nome individual pertencem ao setor das famílias, porque o património da empresa não está separado do património familiar. Seria uma sociedade não financeira apenas se o negócio estivesse constituído como sociedade (por exemplo, uma sociedade por quotas).' },

  { id: 'u8-03', u: 'u8',
    p: 'A Caixa Geral de Depósitos, banco detido pelo Estado, e uma companhia de seguros privada pertencem ambas ao setor institucional',
    o: ['das administrações públicas.',
        'das sociedades não financeiras.',
        'das sociedades financeiras.',
        'das famílias.'],
    c: 2,
    e: 'Bancos, seguradoras e fundos de pensões realizam intermediação financeira ou atividades de seguro, pelo que são sociedades financeiras. O facto de a CGD ser propriedade do Estado não a coloca nas administrações públicas: a classificação depende da função principal e dos recursos, não do proprietário.' },

  { id: 'u8-04', u: 'u8',
    p: 'A Segurança Social e a Câmara Municipal de Braga pertencem ao setor institucional',
    o: ['das instituições sem fim lucrativo ao serviço das famílias.',
        'das sociedades financeiras.',
        'das sociedades não financeiras.',
        'das administrações públicas.'],
    c: 3,
    e: 'As administrações públicas incluem a administração central, regional e local (como as câmaras municipais) e os fundos de segurança social. Apesar de não ter fins lucrativos, a Segurança Social não é uma ISFLSF, porque é financiada por contribuições obrigatórias e tem como função redistribuir o rendimento.' },

  { id: 'u8-05', u: 'u8',
    p: 'A Santa Casa da Misericórdia de uma vila, que gere um lar de idosos e uma creche e é financiada por quotizações, donativos e comparticipações, pertence ao setor institucional',
    o: ['das administrações públicas.',
        'das instituições sem fim lucrativo ao serviço das famílias.',
        'das sociedades não financeiras.',
        'das famílias.'],
    c: 1,
    e: 'As Misericórdias e outras IPSS produzem serviços não mercantis destinados às famílias e financiam-se sobretudo com contribuições voluntárias, pelo que são ISFLSF. Receber apoios do Estado não as torna administrações públicas, já que são entidades privadas e não cobram impostos.' },

  { id: 'u8-06', u: 'u8',
    p: 'Uma empresa de transportes urbanos detida a 100% por um município, que vende bilhetes a preços que cobrem a maior parte dos seus custos, pertence ao setor institucional',
    o: ['das sociedades não financeiras.',
        'das administrações públicas.',
        'das instituições sem fim lucrativo ao serviço das famílias.',
        'das sociedades financeiras.'],
    c: 0,
    e: 'Uma empresa pública que produz bens ou serviços mercantis não financeiros, vendidos a preços que cobrem em grande parte os custos, é uma sociedade não financeira. A opção das administrações públicas é a armadilha: estas produzem serviços não mercantis e financiam-se com impostos, e não com vendas.' },

  { id: 'u8-07', u: 'u8',
    p: 'Os recursos principais do setor das administrações públicas são',
    o: ['as receitas das vendas de bens e serviços a preços de mercado.',
        'as quotizações e os donativos voluntários dos associados.',
        'os juros, as comissões e os prémios de seguro cobrados.',
        'os impostos e as contribuições sociais obrigatórias.'],
    c: 3,
    e: 'As administrações públicas financiam-se sobretudo através de pagamentos obrigatórios: impostos e contribuições sociais. As quotizações e donativos voluntários são os recursos típicos das ISFLSF, que, tal como o Estado, não têm fins lucrativos, mas cujas receitas não são obrigatórias.' },

  { id: 'u8-08', u: 'u8',
    p: 'Os recursos principais das instituições sem fim lucrativo ao serviço das famílias provêm',
    o: ['das receitas das vendas dos bens que produzem.',
        'dos impostos cobrados aos seus utentes.',
        'de contribuições voluntárias, como quotizações e donativos.',
        'dos juros cobrados pelos empréstimos que concedem.'],
    c: 2,
    e: 'As ISFLSF (associações, clubes, sindicatos, IPSS) vivem sobretudo de quotizações, donativos e rendimentos de propriedade, podendo também receber apoios públicos. Não cobram impostos, que são exclusivos das administrações públicas, nem vivem principalmente de vendas, como as sociedades não financeiras.' },

  { id: 'u8-09', u: 'u8',
    p: 'Na contabilidade nacional, o resto do mundo corresponde',
    o: ['ao conjunto dos países da União Europeia com que Portugal comercia.',
        'ao conjunto das empresas estrangeiras com filiais instaladas em Portugal.',
        'ao conjunto das unidades não residentes que realizam operações com unidades residentes.',
        'ao conjunto de todas as unidades institucionais de nacionalidade estrangeira.'],
    c: 2,
    e: 'O resto do mundo agrupa as unidades não residentes, isto é, sem centro de interesse económico no território nacional, que se relacionam com as unidades residentes. O critério é a residência e não a nacionalidade: uma filial de uma empresa estrangeira instalada em Portugal é residente e pertence às sociedades não financeiras.' },

  { id: 'u8-10', u: 'u8',
    p: 'Constitui uma operação de repartição',
    o: ['a concessão de um crédito à habitação por um banco.',
        'a compra de uma casa nova por uma família.',
        'a venda de ações de uma empresa em bolsa.',
        'o pagamento de juros ao banco por uma família endividada.'],
    c: 3,
    e: 'Os juros são um rendimento da propriedade que remunera o capital emprestado, pelo que o seu pagamento é uma operação de repartição. A concessão do crédito, em si, é uma operação financeira, tal como a venda de ações, e a compra da casa é uma operação sobre bens e serviços.' },

  { id: 'u8-11', u: 'u8',
    p: 'Constitui uma operação financeira',
    o: ['a subscrição de ações de uma empresa por um particular.',
        'o pagamento de dividendos aos acionistas de uma empresa.',
        'a exportação de calçado para França.',
        'a atribuição de um subsídio de desemprego.'],
    c: 0,
    e: 'Ao subscrever ações, o particular troca moeda por um ativo financeiro, o que altera os seus ativos financeiros: é uma operação financeira. O pagamento de dividendos é a armadilha mais comum, mas trata-se de uma operação de repartição, porque distribui rendimento (lucros) aos detentores do capital.' },

  { id: 'u8-12', u: 'u8',
    p: 'Constitui uma operação sobre bens e serviços',
    o: ['o pagamento do IRS por um trabalhador.',
        'a compra de um camião por uma empresa de transportes.',
        'a subscrição de obrigações do Tesouro por uma família.',
        'o pagamento de uma pensão de reforma pela Segurança Social.'],
    c: 1,
    e: 'A aquisição de um camião por uma empresa é investimento (formação bruta de capital fixo), uma operação sobre bens e serviços. O pagamento de IRS e o pagamento de pensões são operações de repartição, e a subscrição de obrigações é uma operação financeira.' },

  { id: 'u8-13', u: 'u8',
    p: 'No circuito económico, constitui um fluxo real',
    o: ['o pagamento de salários pelas empresas às famílias.',
        'o pagamento de uma compra num supermercado.',
        'o recebimento de juros de um depósito a prazo.',
        'o trabalho que as famílias fornecem às empresas.'],
    c: 3,
    e: 'Os fluxos reais correspondem a movimentos de bens, serviços e fatores produtivos, como o trabalho. O pagamento de salários é o fluxo monetário que corresponde a esse trabalho, circulando em sentido contrário, das empresas para as famílias.' },

  { id: 'u8-14', u: 'u8',
    p: 'Das situações seguintes, a que corresponde a um fluxo monetário é',
    o: ['a entrega de mobiliário encomendado a um cliente.',
        'as horas de trabalho prestadas por um técnico informático.',
        'o pagamento mensal da renda de casa ao senhorio.',
        'o serviço de transporte prestado por um táxi.'],
    c: 2,
    e: 'Os fluxos monetários são movimentos de moeda, como o pagamento de uma renda. A entrega de mobiliário, o trabalho do técnico e o serviço de táxi são fluxos reais, porque envolvem bens, serviços ou fatores produtivos, aos quais correspondem pagamentos em sentido contrário.' },

  { id: 'u8-15', u: 'u8',
    p: 'No circuito económico simplificado, que relaciona apenas famílias e empresas, verifica-se que',
    o: ['os fluxos reais e os fluxos monetários circulam no mesmo sentido.',
        'a cada fluxo real corresponde um fluxo monetário de igual valor e sentido contrário.',
        'as famílias fornecem bens de consumo e as empresas fornecem trabalho.',
        'as empresas recebem salários e pagam as compras de bens de consumo.'],
    c: 1,
    e: 'No circuito simplificado, as famílias fornecem trabalho e recebem salários, e as empresas fornecem bens de consumo e recebem o seu pagamento. Assim, cada fluxo real tem um fluxo monetário de igual valor que circula em sentido oposto, e não no mesmo sentido.' },

  { id: 'u8-16', u: 'u8',
    p: 'A igualdade «Produto = Rendimento = Despesa» significa que',
    o: ['o valor da produção de um período é igual aos rendimentos por ela gerados e à despesa realizada na sua aquisição.',
        'as famílias gastam sempre em consumo a totalidade do rendimento que recebem num período.',
        'a despesa pública de um período é igual à receita cobrada pelo Estado em impostos.',
        'o valor da produção nacional é sempre igual ao valor das importações do mesmo período.'],
    c: 0,
    e: 'A produção gera rendimentos (salários, juros, rendas, lucros) e esses rendimentos são usados para adquirir a produção, pelo que as três óticas medem a mesma realidade. A igualdade não exige que as famílias consumam todo o rendimento: a parte poupada regressa ao circuito como investimento, que também é despesa.' },

  { id: 'u8-17', u: 'u8',
    p: 'Numa economia fechada e sem Estado, o rendimento foi de 1000 milhões de euros e as famílias gastaram 850 milhões de euros em consumo. Para que o circuito esteja em equilíbrio, o investimento terá de ser de',
    o: ['150 milhões de euros.',
        '850 milhões de euros.',
        '1150 milhões de euros.',
        '1000 milhões de euros.'],
    c: 0,
    e: 'A poupança é o rendimento não consumido: 1000 − 850 = 150 milhões de euros. Numa economia fechada e sem Estado, o equilíbrio do circuito exige que a poupança (fuga) seja igual ao investimento (injeção), pelo que I = S = 150 milhões de euros. O valor de 850 milhões corresponde ao consumo e não ao investimento.' },

  { id: 'u8-18', u: 'u8',
    p: 'Um setor institucional apresenta capacidade de financiamento quando',
    o: ['o seu rendimento disponível é superior à despesa de consumo.',
        'o investimento que realiza é superior à poupança que gera.',
        'a poupança que gera é superior ao investimento que realiza.',
        'as receitas de impostos são superiores às suas despesas correntes.'],
    c: 2,
    e: 'Há capacidade de financiamento quando a poupança excede o investimento, ficando recursos disponíveis para emprestar a outros setores. Ter rendimento superior ao consumo significa apenas ter poupança positiva, o que não basta: se o setor investir mais do que poupa, terá necessidade de financiamento.' },

  { id: 'u8-19', u: 'u8',
    p: 'Nas economias desenvolvidas, o setor institucional que habitualmente apresenta necessidade de financiamento, por investir mais do que a poupança que gera, é o das',
    o: ['famílias.',
        'sociedades financeiras.',
        'instituições sem fim lucrativo ao serviço das famílias.',
        'sociedades não financeiras.'],
    c: 3,
    e: 'As sociedades não financeiras realizam a maior parte do investimento produtivo e a sua poupança (lucros não distribuídos) costuma ser insuficiente para o financiar, pelo que recorrem ao crédito. As famílias, pelo contrário, costumam ter capacidade de financiamento, sendo a sua poupança canalizada pelas sociedades financeiras para as empresas.' },

  { id: 'u8-20', u: 'u8',
    p: 'Se, num dado ano, a soma das capacidades e necessidades de financiamento de todos os setores institucionais residentes for negativa, pode concluir-se que',
    o: ['o Estado registou obrigatoriamente um défice orçamental nesse ano.',
        'a economia nacional teve necessidade de financiamento, coberta pelo resto do mundo.',
        'todos os setores residentes investiram mais do que a poupança que geraram.',
        'a economia nacional teve capacidade de financiamento face ao resto do mundo.'],
    c: 1,
    e: 'A soma dos saldos dos setores residentes dá a capacidade ou necessidade de financiamento da economia face ao resto do mundo; sendo negativa, o país recorreu à poupança externa. Não se pode concluir que todos os setores tiveram necessidade, nem que o Estado teve défice: basta que as necessidades de alguns setores superem as capacidades dos restantes.' },
);
