/* Perguntas de escolha múltipla — Economia A, unidades 1 a 4 */
(window.ECO_PERGUNTAS = window.ECO_PERGUNTAS || []).push(

  /* ===== Unidade 1 — A atividade económica e a ciência económica ===== */
  { id: 'u1-01', u: 'u1',
    p: 'O problema económico fundamental resulta de',
    o: ['os preços dos bens serem demasiado elevados para a maioria das famílias.',
        'as necessidades serem ilimitadas e os recursos escassos terem usos alternativos.',
        'os recursos naturais estarem a esgotar-se em todo o planeta.',
        'as empresas procurarem o lucro em vez de satisfazer necessidades.'],
    c: 1,
    e: 'A economia existe porque os recursos são escassos face a necessidades ilimitadas e podem ser usados de várias formas, o que obriga a escolher. Os preços elevados são uma consequência da escassez, não a sua causa; e mesmo com preços baixos continuaria a ser preciso escolher.' },

  { id: 'u1-02', u: 'u1',
    p: 'A Joana tem 20 € e hesita entre um bilhete para um concerto, um livro e um jantar com amigas, cada um a custar 20 €. Prefere o concerto, depois o livro e, por último, o jantar. Se comprar o bilhete do concerto, o custo de oportunidade da sua escolha é',
    o: ['os 20 € que pagou pelo bilhete.',
        'o livro e o jantar com as amigas.',
        'o livro.',
        'o jantar com as amigas.'],
    c: 2,
    e: 'O custo de oportunidade é o valor da melhor alternativa a que se renuncia — aqui, o livro, a segunda opção preferida. Não é a soma de todas as alternativas (a Joana só podia ter escolhido uma delas) nem o preço pago pelo bilhete.' },

  { id: 'u1-03', u: 'u1',
    p: 'Em economia, diz-se que um recurso é escasso quando',
    o: ['existe em quantidades muito reduzidas na natureza.',
        'o seu preço de mercado é muito elevado.',
        'está em vias de se esgotar num futuro próximo.',
        'é insuficiente para satisfazer todas as necessidades a que poderia destinar-se.'],
    c: 3,
    e: 'A escassez em economia é relativa: compara a quantidade disponível com as necessidades que o recurso poderia satisfazer. Um recurso abundante, como a água potável, pode ser escasso; ser raro na natureza não é o critério.' },

  { id: 'u1-04', u: 'u1',
    p: 'Constitui um exemplo de bem livre',
    o: ['a luz do sol que ilumina uma praia.',
        'a água que chega às torneiras de uma casa.',
        'o oxigénio engarrafado usado num hospital.',
        'a lenha vendida para as lareiras no inverno.'],
    c: 0,
    e: 'Um bem livre existe em abundância, não resulta de atividade produtiva e não tem preço — é o caso da luz solar. A água canalizada é um bem económico, porque exige captação, tratamento e distribuição e é paga pelas famílias.' },

  { id: 'u1-05', u: 'u1',
    p: 'A D. Rosa compra um saco de farinha para fazer um bolo de aniversário e uma padaria compra um saco igual para fazer pão. Pode concluir-se que a farinha é',
    o: ['um bem de consumo em ambos os casos, porque é um bem alimentar.',
        'um bem de consumo no primeiro caso e um bem de produção no segundo.',
        'um bem de produção em ambos os casos, porque é sempre transformada.',
        'um bem livre no primeiro caso e um bem económico no segundo.'],
    c: 1,
    e: 'A classificação de um bem depende da utilização que lhe é dada: comprada por uma família para satisfazer diretamente uma necessidade, a farinha é bem de consumo; comprada por uma empresa para produzir pão, é bem de produção (intermédio). O facto de ser transformada em casa não a torna bem de produção, porque a família não produz para o mercado.' },

  { id: 'u1-06', u: 'u1',
    p: 'Constituem um par de bens complementares',
    o: ['o café e o chá.',
        'a manteiga e a margarina.',
        'a impressora e os tinteiros.',
        'o comboio e o autocarro.'],
    c: 2,
    e: 'Bens complementares são utilizados em conjunto para satisfazer uma necessidade: a impressora não serve sem tinteiros. A manteiga e a margarina, tal como o café e o chá ou o comboio e o autocarro, são bens sucedâneos, porque um pode substituir o outro.' },

  { id: 'u1-07', u: 'u1',
    p: 'Depois de uma forte subida do preço do azeite, muitas famílias passaram a cozinhar com óleo de girassol. Este comportamento indica que o azeite e o óleo de girassol são',
    o: ['bens complementares.',
        'bens livres.',
        'bens de produção.',
        'bens sucedâneos.'],
    c: 3,
    e: 'Os bens sucedâneos satisfazem a mesma necessidade e podem substituir-se; quando um encarece, os consumidores tendem a trocá-lo pelo outro. Se fossem complementares, a subida do preço do azeite faria diminuir também o consumo de óleo, e não aumentá-lo.' },

  { id: 'u1-08', u: 'u1',
    p: 'É exemplo de um bem de consumo duradouro',
    o: ['uma máquina de lavar roupa utilizada numa casa.',
        'o detergente utilizado na máquina de lavar de uma casa.',
        'uma máquina de lavar roupa utilizada numa lavandaria.',
        'uma sessão de cinema num centro comercial.'],
    c: 0,
    e: 'A máquina usada por uma família satisfaz diretamente uma necessidade (bem de consumo) e permite muitas utilizações (duradouro). A mesma máquina numa lavandaria é utilizada para prestar um serviço a clientes, sendo por isso um bem de produção; o detergente esgota-se numa só utilização.' },

  { id: 'u1-09', u: 'u1',
    p: 'No circuito económico simplificado, constitui um fluxo real',
    o: ['os salários pagos pelas empresas às famílias.',
        'o trabalho fornecido pelas famílias às empresas.',
        'as despesas de consumo das famílias nas empresas.',
        'os juros e lucros recebidos pelas famílias.'],
    c: 1,
    e: 'Os fluxos reais correspondem à circulação de bens, serviços e fatores produtivos, como o trabalho que as famílias prestam às empresas. Os salários são o fluxo monetário que remunera esse trabalho e circula em sentido contrário.' },

  { id: 'u1-10', u: 'u1',
    p: 'No circuito económico, a relação entre os fluxos reais e os fluxos monetários caracteriza-se por',
    o: ['a cada fluxo real corresponder um fluxo monetário com o mesmo sentido.',
        'os fluxos reais incluírem apenas a circulação de bens materiais.',
        'a cada fluxo real corresponder um fluxo monetário de sentido contrário.',
        'os fluxos monetários serem sempre superiores aos fluxos reais.'],
    c: 2,
    e: 'Sempre que um bem, serviço ou fator produtivo passa de um agente para outro, a moeda que o paga circula no sentido inverso e com o mesmo valor. Os fluxos reais não se limitam a bens materiais: incluem serviços e o próprio trabalho.' },

  { id: 'u1-11', u: 'u1',
    p: 'A função principal das administrações públicas enquanto agente económico é',
    o: ['produzir bens e serviços mercantis com o objetivo de obter lucro.',
        'recolher poupanças e conceder crédito aos outros agentes.',
        'consumir bens e serviços e fornecer trabalho às empresas.',
        'produzir serviços não mercantis e redistribuir o rendimento.'],
    c: 3,
    e: 'O Estado presta serviços não mercantis (educação, saúde, segurança, justiça), financiados sobretudo por impostos, e redistribui o rendimento através de impostos e prestações sociais. Produzir para o mercado com fim lucrativo é a função das empresas.' },

  { id: 'u1-12', u: 'u1',
    p: 'A função principal das instituições financeiras (bancos e seguradoras) é',
    o: ['financiar a atividade económica, captando poupanças e concedendo crédito.',
        'produzir bens materiais destinados a ser vendidos no mercado.',
        'redistribuir o rendimento através de impostos e subsídios.',
        'representar os interesses dos trabalhadores junto das empresas.'],
    c: 0,
    e: 'Bancos e outras instituições financeiras fazem a intermediação entre quem poupa e quem precisa de financiamento; as seguradoras cobrem riscos. Redistribuir o rendimento através de impostos e subsídios é função das administrações públicas.' },

  { id: 'u1-13', u: 'u1',
    p: 'O aumento do turismo em Lisboa fez subir as rendas, levou muitos moradores a sair dos bairros históricos, alterou o comércio local e provocou debates na Assembleia Municipal. Esta situação ilustra',
    o: ['que os fenómenos sociais podem ser explicados por uma única ciência social.',
        'o caráter multidimensional da realidade social.',
        'que a economia estuda sobretudo fenómenos políticos.',
        'a separação rigorosa entre as várias ciências sociais.'],
    c: 1,
    e: 'O mesmo fenómeno tem, simultaneamente, dimensões económica (rendas, comércio), social e demográfica (saída de moradores) e política (debate autárquico). Por isso, a sua compreensão exige o contributo de várias ciências sociais, e não de uma só.' },

  { id: 'u1-14', u: 'u1',
    p: 'As diferentes ciências sociais distinguem-se entre si porque',
    o: ['cada uma estuda uma realidade social diferente e independente.',
        'só a Economia utiliza métodos científicos rigorosos.',
        'cada uma analisa a realidade social a partir de um ponto de vista próprio.',
        'umas estudam os indivíduos e outras estudam apenas as instituições.'],
    c: 2,
    e: 'Todas as ciências sociais estudam a mesma realidade social, mas cada uma privilegia um aspeto dela — o seu objeto de estudo. A ideia de que estudam realidades separadas é errada, precisamente porque a realidade social é multidimensional e as ciências sociais são interdependentes.' },

  { id: 'u1-15', u: 'u1',
    p: 'Constitui um objeto de estudo da macroeconomia',
    o: ['a decisão de uma família sobre como gastar o seu rendimento.',
        'a formação do preço das cerejas no mercado do Fundão.',
        'a escolha de uma empresa entre contratar ou comprar máquinas.',
        'a evolução da taxa de desemprego em Portugal.'],
    c: 3,
    e: 'A macroeconomia estuda a economia no seu conjunto, através de grandezas agregadas como o desemprego nacional, a inflação ou o crescimento. O preço num mercado concreto, tal como as decisões de uma família ou de uma empresa, são objeto da microeconomia.' },

  { id: 'u1-16', u: 'u1',
    p: 'O Rui recusou trabalhar no sábado num café, onde ganharia 30 €, para ir a um concerto gratuito. Trabalhar era a melhor alternativa de que dispunha. O custo de oportunidade de ir ao concerto',
    o: ['corresponde aos 30 € que o Rui deixou de ganhar.',
        'é nulo, porque o concerto era gratuito.',
        'é nulo, porque o Rui escolheu o que mais lhe agradava.',
        'corresponde ao preço que o bilhete teria noutro dia.'],
    c: 0,
    e: 'Mesmo sem pagar bilhete, o Rui renunciou à melhor alternativa, o trabalho que lhe renderia 30 €. O custo de oportunidade não é o preço pago: existe sempre que se sacrifica uma alternativa, incluindo o uso do tempo.' },

  { id: 'u1-17', u: 'u1',
    p: 'A distribuição de salários, rendas, juros e lucros pelos agentes que participaram na produção corresponde, na atividade económica, à',
    o: ['circulação dos bens.',
        'repartição dos rendimentos.',
        'utilização dos rendimentos.',
        'produção de bens e serviços.'],
    c: 1,
    e: 'A repartição é a fase em que o rendimento gerado na produção é distribuído pelos que forneceram fatores produtivos (salários ao trabalho, rendas, juros e lucros). A utilização dos rendimentos é a fase seguinte, em que esses rendimentos são consumidos ou poupados.' },

  { id: 'u1-18', u: 'u1',
    p: 'Uma aula de explicações de Matemática, paga pelos pais de um aluno, é',
    o: ['um bem livre imaterial.',
        'um bem económico material.',
        'um bem económico imaterial.',
        'um bem de produção duradouro.'],
    c: 2,
    e: 'É um serviço (bem imaterial, intangível) e é um bem económico, porque é escasso, resulta de uma atividade produtiva e tem preço. Não é material, pois não tem existência física.' },

  { id: 'u1-19', u: 'u1',
    p: 'Um caminhante bebe água de uma nascente numa serra isolada; noutro dia, compra a mesma água, engarrafada, num supermercado. Relativamente a esta água, pode afirmar-se que',
    o: ['é sempre um bem económico, porque satisfaz uma necessidade primária.',
        'é sempre um bem livre, porque é um recurso natural.',
        'é um bem económico na nascente e um bem livre no supermercado.',
        'é um bem livre na nascente e um bem económico no supermercado.'],
    c: 3,
    e: 'Na nascente, a água é abundante, não exigiu produção e não tem preço: é um bem livre. Engarrafada, resultou de captação, embalagem e transporte, é escassa e tem preço: é um bem económico. Satisfazer uma necessidade primária não determina se o bem é livre ou económico.' },

  { id: 'u1-20', u: 'u1',
    p: 'No circuito económico simplificado, com apenas famílias e empresas, admite-se que',
    o: ['as famílias gastam todo o seu rendimento em consumo.',
        'as famílias depositam parte do rendimento nos bancos.',
        'as empresas pagam impostos às administrações públicas.',
        'as empresas vendem parte da produção ao estrangeiro.'],
    c: 0,
    e: 'O modelo simplificado considera uma economia fechada, sem Estado e sem poupança: todo o rendimento recebido pelas famílias regressa às empresas sob a forma de despesas de consumo. A poupança, o Estado e o resto do mundo só aparecem em circuitos mais completos.' },

  /* ===== Unidade 2 — Necessidades e consumo ===== */
  { id: 'u2-01', u: 'u2',
    p: 'É exemplo de uma necessidade primária',
    o: ['ter um telemóvel com acesso à internet.',
        'fazer uma viagem de férias ao estrangeiro.',
        'beber água para evitar a desidratação.',
        'assistir a um jogo de futebol no estádio.'],
    c: 2,
    e: 'As necessidades primárias são fisiológicas, indispensáveis à sobrevivência, como beber água. Ter telemóvel ou viajar são necessidades secundárias (sociais ou civilizacionais), que dependem do nível de desenvolvimento, por muito importantes que se tenham tornado.' },

  { id: 'u2-02', u: 'u2',
    p: 'É exemplo de uma necessidade coletiva',
    o: ['a segurança pública.',
        'o vestuário.',
        'o transporte em carro próprio.',
        'a alimentação de uma família.'],
    c: 0,
    e: 'A segurança pública é sentida pela sociedade no seu conjunto e satisfeita coletivamente, por exemplo através da polícia. O vestuário, a alimentação e o transporte próprio são necessidades individuais, mesmo que sejam sentidas por muitas pessoas ao mesmo tempo.' },

  { id: 'u2-03', u: 'u2',
    p: 'Depois de comer duas fatias de pizza, o Miguel já não quer comer mais. Esta situação ilustra que as necessidades são',
    o: ['ilimitadas.',
        'substituíveis.',
        'variáveis no espaço.',
        'saciáveis.'],
    c: 3,
    e: 'Cada necessidade concreta, isoladamente, pode ser satisfeita — é saciável. O caráter ilimitado refere-se ao conjunto das necessidades (satisfeita uma, surgem outras), e não a uma necessidade em particular.' },

  { id: 'u2-04', u: 'u2',
    p: 'Há quarenta anos poucas famílias portuguesas sentiam necessidade de acesso à internet; hoje é considerado quase indispensável. Esta evolução ilustra',
    o: ['o caráter saciável das necessidades.',
        'a variabilidade das necessidades no tempo.',
        'a passagem de necessidades coletivas a individuais.',
        'a lei de Engel.'],
    c: 1,
    e: 'As necessidades variam no tempo e no espaço, acompanhando o desenvolvimento técnico, o rendimento e a cultura. A lei de Engel relaciona o rendimento com o peso da alimentação no orçamento, o que não está em causa neste exemplo.' },

  { id: 'u2-05', u: 'u2',
    p: 'Constitui consumo intermédio',
    o: ['o pão comprado numa pastelaria por uma família.',
        'o forno comprado por uma pastelaria.',
        'a farinha utilizada por uma pastelaria para fazer bolos.',
        'o bolo de aniversário comprado por uma família.'],
    c: 2,
    e: 'O consumo intermédio corresponde a bens utilizados e transformados no processo produtivo, como a farinha que se incorpora nos bolos. O forno não é consumo intermédio: é capital fixo, que participa em muitos ciclos produtivos e não se esgota numa só utilização.' },

  { id: 'u2-06', u: 'u2',
    p: 'Uma consulta num centro de saúde do Serviço Nacional de Saúde, sem custos para o utente, constitui consumo',
    o: ['privado e coletivo.',
        'público e individual.',
        'público e coletivo.',
        'privado e individual.'],
    c: 1,
    e: 'É consumo público porque a despesa é suportada pelo Estado; é individual porque satisfaz a necessidade de uma pessoa concreta, o utente. O erro frequente é confundir «público» com «coletivo»: são critérios diferentes (quem paga e que tipo de necessidade é satisfeita).' },

  { id: 'u2-07', u: 'u2',
    p: 'A Beatriz comprou uns ténis da mesma marca e modelo que viu serem usados por uma figura pública que admira. Este comportamento é explicado pelo',
    o: ['efeito snob.',
        'consumerismo.',
        'aumento do rendimento.',
        'efeito de imitação.'],
    c: 3,
    e: 'O efeito de imitação (ou de demonstração) leva os consumidores a copiar os padrões de consumo de grupos ou pessoas de referência. O efeito snob é o oposto: consumir bens exclusivos para se distinguir dos outros, e não para se parecer com eles.' },

  { id: 'u2-08', u: 'u2',
    p: 'O Sr. Almeida deixou de usar uma marca de relógios quando esta passou a ser vendida a preços acessíveis nos hipermercados. Este comportamento ilustra o',
    o: ['efeito snob.',
        'efeito de imitação.',
        'consumo sustentável.',
        'efeito do crédito.'],
    c: 0,
    e: 'O efeito snob leva o consumidor a procurar bens raros e exclusivos e a abandoná-los quando se generalizam. Se se tratasse de efeito de imitação, o Sr. Almeida passaria a consumir aquilo que os outros consomem, e não a afastar-se desse consumo.' },

  { id: 'u2-09', u: 'u2',
    p: 'Segundo a lei de Engel, à medida que o rendimento de uma família aumenta,',
    o: ['diminui o valor gasto em alimentação.',
        'diminui o peso das despesas com alimentação no total das despesas.',
        'aumenta o peso das despesas com alimentação no total das despesas.',
        'o peso de todas as categorias de despesa se mantém constante.'],
    c: 1,
    e: 'A lei de Engel refere-se ao peso relativo: a percentagem do orçamento gasta em alimentação diminui quando o rendimento aumenta. O valor em euros gasto em alimentação pode até aumentar — dizer que diminui é o erro mais comum.' },

  { id: 'u2-10', u: 'u2',
    p: 'Uma família tem um rendimento disponível mensal de 2000 €, uma despesa total de consumo de 1600 € e gasta 400 € em alimentação. O coeficiente orçamental da alimentação é',
    o: ['20 %.',
        '4 %.',
        '25 %.',
        '40 %.'],
    c: 2,
    e: 'O coeficiente orçamental mede o peso de uma despesa na despesa total de consumo: 400 ÷ 1600 × 100 = 25 %. Obter 20 % resulta de dividir pelo rendimento disponível (400 ÷ 2000), que não é a base de cálculo deste indicador.' },

  { id: 'u2-11', u: 'u2',
    p: 'Em 2015, a família Costa destinava 30 % da sua despesa à alimentação; em 2025, com um rendimento mais elevado, destina 22 %, embora gaste mais euros em alimentação do que antes. Esta evolução',
    o: ['é compatível com a lei de Engel.',
        'contraria a lei de Engel, porque o valor gasto em alimentação aumentou.',
        'contraria a lei de Engel, porque o rendimento aumentou.',
        'não pode ser relacionada com a lei de Engel.'],
    c: 0,
    e: 'A lei de Engel prevê que, com o aumento do rendimento, diminua a percentagem da despesa em alimentação, o que se verifica (de 30 % para 22 %). O aumento do valor absoluto gasto em alimentação não contraria a lei, porque esta se refere ao peso relativo.' },

  { id: 'u2-12', u: 'u2',
    p: 'O movimento organizado que visa defender os direitos e interesses dos consumidores designa-se',
    o: ['consumismo.',
        'sociedade de consumo.',
        'efeito de demonstração.',
        'consumerismo.'],
    c: 3,
    e: 'O consumerismo é o movimento de defesa dos consumidores, de que a DECO é exemplo em Portugal. O consumismo é o oposto em espírito: designa o consumo excessivo e irrefletido, característico da sociedade de consumo.' },

  { id: 'u2-13', u: 'u2',
    p: 'A tendência para adquirir bens de forma excessiva e irrefletida, muitas vezes sem necessidade real, designa-se',
    o: ['consumerismo.',
        'consumo coletivo.',
        'consumismo.',
        'consumo intermédio.'],
    c: 2,
    e: 'Consumismo é o consumo excessivo, associado à publicidade, à moda e ao crédito fácil. O consumerismo, apesar do nome parecido, é o movimento de defesa dos consumidores.' },

  { id: 'u2-14', u: 'u2',
    p: 'A obrigação de indicar nos rótulos dos alimentos os ingredientes, os alergénios e o prazo de validade concretiza sobretudo o direito do consumidor',
    o: ['à participação por via representativa.',
        'à informação para o consumo.',
        'à proteção jurídica e a uma justiça acessível.',
        'à formação e à educação para o consumo.'],
    c: 1,
    e: 'A rotulagem fornece ao consumidor informação clara sobre o produto, concretizando o direito à informação para o consumo. O direito à formação e educação refere-se a ações que desenvolvem competências dos consumidores (por exemplo, na escola), e não à informação prestada sobre um produto concreto.' },

  { id: 'u2-15', u: 'u2',
    p: 'É uma característica da sociedade de consumo',
    o: ['a produção em massa, com forte recurso à publicidade e ao crédito.',
        'o predomínio do autoconsumo e da produção familiar.',
        'a escassez generalizada de bens essenciais.',
        'o predomínio do setor primário no emprego.'],
    c: 0,
    e: 'A sociedade de consumo, típica dos países desenvolvidos, assenta na produção em massa de uma grande variedade de bens, estimulada pela publicidade e pelo crédito. O autoconsumo e o predomínio do setor primário caracterizam sociedades tradicionais, pouco desenvolvidas.' },

  { id: 'u2-16', u: 'u2',
    p: 'Qual dos seguintes comportamentos corresponde a um consumo sustentável?',
    o: ['Trocar de telemóvel todos os anos para acompanhar as novidades.',
        'Comprar fruta importada fora da época por ser mais barata.',
        'Comprar roupa em grande quantidade nas épocas de saldos.',
        'Mandar reparar o computador em vez de comprar um novo.'],
    c: 3,
    e: 'Reparar prolonga a vida útil dos bens, reduzindo o consumo de recursos e a produção de resíduos. Comprar muito nos saldos pode parecer poupança, mas estimula compras desnecessárias e desperdício, contrariando a lógica de consumo sustentável.' },

  { id: 'u2-17', u: 'u2',
    p: 'Quando o rendimento disponível de uma família aumenta, em regra,',
    o: ['o consumo diminui, porque a família passa a poupar tudo o que ganha a mais.',
        'o consumo aumenta na mesma proporção em todas as categorias de bens.',
        'o consumo aumenta e a sua estrutura altera-se.',
        'o consumo mantém-se, porque as necessidades são saciáveis.'],
    c: 2,
    e: 'Com mais rendimento a família consome mais, mas não da mesma forma em tudo: o peso da alimentação desce e o de bens como lazer, saúde e educação sobe, o que altera a estrutura do consumo. Supor um aumento igual em todas as categorias contraria a lei de Engel.' },

  { id: 'u2-18', u: 'u2',
    p: 'Se o preço dos bilhetes de comboio entre Lisboa e Porto aumentar significativamente, mantendo-se tudo o resto igual, é de esperar que',
    o: ['aumente a procura de bilhetes de comboio.',
        'aumente a procura de viagens de autocarro nesse percurso.',
        'diminua a procura de viagens de autocarro nesse percurso.',
        'a procura de transportes nesse percurso não se altere.'],
    c: 1,
    e: 'O comboio e o autocarro são sucedâneos: quando um encarece, parte dos consumidores passa a usar o outro. A procura de autocarro só diminuiria se fossem bens complementares, o que não é o caso.' },

  { id: 'u2-19', u: 'u2',
    p: 'Relativamente à publicidade, é correto afirmar que',
    o: ['se limita a informar os consumidores sobre as características dos bens.',
        'só influencia o consumo das famílias com rendimentos elevados.',
        'deixou de influenciar o consumo com a difusão da internet.',
        'informa, mas sobretudo persuade e pode criar novas necessidades.'],
    c: 3,
    e: 'A publicidade tem uma função informativa, mas o seu objetivo principal é persuadir, associando os produtos a estilos de vida e criando desejos de consumo. A ideia de que apenas informa ignora esta função persuasiva, que a internet e as redes sociais até reforçaram.' },

  { id: 'u2-20', u: 'u2',
    p: 'Uma descida das taxas de juro praticadas pelos bancos tende a',
    o: ['estimular a compra a crédito de bens de consumo duradouros.',
        'reduzir o consumo, porque as famílias preferem poupar mais.',
        'aumentar o peso da alimentação nas despesas das famílias.',
        'diminuir o recurso ao crédito por parte das famílias.'],
    c: 0,
    e: 'Com juros mais baixos, o crédito fica mais barato e as famílias tendem a comprar mais bens duradouros, como automóveis e eletrodomésticos, recorrendo a empréstimos. Juros baixos tornam a poupança menos compensadora, pelo que não incentivam as famílias a poupar mais.' },

  /* ===== Unidade 3 — A produção de bens e serviços ===== */
  { id: 'u3-01', u: 'u3',
    p: 'Em sentido económico, constitui uma atividade de produção',
    o: ['a compra de um automóvel por uma família.',
        'a consulta realizada por uma médica num hospital.',
        'a chuva que enche a albufeira de uma barragem.',
        'o depósito das poupanças de uma família num banco.'],
    c: 1,
    e: 'Produzir é criar bens ou serviços combinando fatores produtivos; a consulta médica é a produção de um serviço. A compra de um automóvel é consumo e o depósito é uma aplicação da poupança; a chuva é um fenómeno natural, sem intervenção de fatores produtivos.' },

  { id: 'u3-02', u: 'u3',
    p: 'Uma empresa de construção civil insere-se no setor',
    o: ['secundário.',
        'primário.',
        'terciário.',
        'quaternário.'],
    c: 0,
    e: 'O setor secundário inclui as atividades de transformação, como a indústria transformadora, a construção e a produção de energia. O terciário engloba os serviços (comércio, transportes, ensino, saúde), e não a construção de edifícios.' },

  { id: 'u3-03', u: 'u3',
    p: 'A terciarização de uma economia consiste',
    o: ['na diminuição do número de empresas de serviços.',
        'na passagem de trabalhadores do setor terciário para a indústria.',
        'no aumento da produção industrial destinada à exportação.',
        'no aumento do peso do setor terciário no emprego e na produção.'],
    c: 3,
    e: 'Terciarização é o aumento da importância relativa dos serviços na população empregada e no VAB, fenómeno típico dos países desenvolvidos, incluindo Portugal. A passagem de trabalhadores para a indústria corresponde a uma industrialização, o processo inverso.' },

  { id: 'u3-04', u: 'u3',
    p: 'Num país com 10 400 000 habitantes, há 4 836 000 empregados e 364 000 desempregados. A taxa de desemprego é',
    o: ['3,5 %.',
        '7,5 %.',
        '7 %.',
        '50 %.'],
    c: 2,
    e: 'População ativa = 4 836 000 + 364 000 = 5 200 000. Taxa de desemprego = 364 000 ÷ 5 200 000 × 100 = 7 %. Os 3,5 % resultam do erro de dividir pela população total; os 7,5 % de dividir apenas pelos empregados.' },

  { id: 'u3-05', u: 'u3',
    p: 'Num país com 10 000 000 habitantes, há 4 370 000 empregados e 230 000 desempregados. A taxa de atividade é',
    o: ['43,7 %.',
        '46 %.',
        '5 %.',
        '54 %.'],
    c: 1,
    e: 'População ativa = 4 370 000 + 230 000 = 4 600 000. Taxa de atividade = 4 600 000 ÷ 10 000 000 × 100 = 46 %. Os 43,7 % resultam de esquecer que os desempregados também fazem parte da população ativa; 5 % é a taxa de desemprego (230 000 ÷ 4 600 000 × 100).' },

  { id: 'u3-06', u: 'u3',
    p: 'Qual das seguintes pessoas é considerada desempregada?',
    o: ['O Luís, 20 anos, estudante universitário a tempo inteiro, que não procura trabalho.',
        'A D. Graça, 68 anos, reformada, que não procura trabalho.',
        'O Pedro, 35 anos, sem emprego, que desistiu de procurar por achar que não encontra.',
        'A Marta, 24 anos, sem emprego, disponível e a enviar currículos e ir a entrevistas.'],
    c: 3,
    e: 'Para ser desempregado é preciso, simultaneamente, não ter emprego, estar disponível para trabalhar e procurar ativamente emprego — só a Marta cumpre as três condições. O Pedro, apesar de não ter emprego, deixou de procurar, pelo que é considerado inativo.' },

  { id: 'u3-07', u: 'u3',
    p: 'Numa fábrica de conservas de peixe, constitui capital técnico circulante',
    o: ['o azeite e as latas utilizados na produção.',
        'as máquinas de enlatar.',
        'o edifício onde funciona a fábrica.',
        'as ações que a empresa detém noutra sociedade.'],
    c: 0,
    e: 'O capital circulante esgota-se num único ciclo produtivo, incorporando-se no produto, como o azeite e as latas. As máquinas e o edifício são capital fixo (várias utilizações); as ações são capital financeiro.' },

  { id: 'u3-08', u: 'u3',
    p: 'Constitui capital financeiro de uma empresa',
    o: ['o camião utilizado nas entregas.',
        'o stock de matérias-primas em armazém.',
        'os depósitos bancários e as obrigações que possui.',
        'os computadores usados no escritório.'],
    c: 2,
    e: 'O capital financeiro é constituído pelos meios monetários e títulos (depósitos, ações, obrigações) que permitem adquirir capital técnico. As matérias-primas em armazém são capital técnico circulante, e o camião e os computadores são capital técnico fixo.' },

  { id: 'u3-09', u: 'u3',
    p: 'Numa economia, num dado ano, a FBCF foi de 900 000 €, a variação de existências de 100 000 € e as amortizações de 350 000 €. O investimento líquido foi de',
    o: ['550 000 €.',
        '650 000 €.',
        '1 000 000 €.',
        '1 350 000 €.'],
    c: 1,
    e: 'Investimento bruto = 900 000 + 100 000 = 1 000 000 €. Investimento líquido = 1 000 000 − 350 000 = 650 000 €. Os 550 000 € resultam de esquecer a variação de existências, que também faz parte do investimento.' },

  { id: 'u3-10', u: 'u3',
    p: 'Se, num ano, o investimento bruto de uma empresa for inferior às amortizações,',
    o: ['o investimento líquido é positivo e o capital aumenta.',
        'a empresa está obrigatoriamente a ter prejuízo.',
        'a FBCF é negativa.',
        'o stock de capital da empresa diminui.'],
    c: 3,
    e: 'As amortizações medem o desgaste do capital; se o investimento bruto não chega para o repor, o investimento líquido é negativo e o stock de capital diminui. A FBCF não é negativa (a empresa continua a comprar bens de capital), apenas insuficiente para compensar o desgaste.' },

  { id: 'u3-11', u: 'u3',
    p: 'Numa empresa, 12 trabalhadores, com um horário de 8 horas por dia, produzem 1920 unidades por dia. A produtividade média do trabalho por hora é de',
    o: ['20 unidades.',
        '160 unidades.',
        '240 unidades.',
        '96 unidades.'],
    c: 0,
    e: 'Horas de trabalho por dia = 12 × 8 = 96. Produtividade horária = 1920 ÷ 96 = 20 unidades por hora de trabalho. Os 160 correspondem à produtividade por trabalhador e por dia (1920 ÷ 12) e os 240 à produção total por hora (1920 ÷ 8), não por hora de trabalho.' },

  { id: 'u3-12', u: 'u3',
    p: 'Em 2024, uma empresa produziu 1200 unidades com 10 trabalhadores; em 2025 produziu 1560 unidades com 12 trabalhadores. A produtividade média do trabalho',
    o: ['aumentou 30 %.',
        'diminuiu, porque o número de trabalhadores aumentou.',
        'aumentou cerca de 8,3 %.',
        'manteve-se constante.'],
    c: 2,
    e: 'Produtividade em 2024 = 1200 ÷ 10 = 120; em 2025 = 1560 ÷ 12 = 130. Variação = (130 − 120) ÷ 120 × 100 ≈ 8,3 %. Os 30 % correspondem ao aumento da produção (1560 ÷ 1200), que não é o mesmo que o aumento da produtividade.' },

  { id: 'u3-13', u: 'u3',
    p: 'Uma empresa de calçado de Felgueiras instala um sistema robotizado de corte que permite produzir mais pares por hora com os mesmos trabalhadores. Trata-se de',
    o: ['uma economia de escala resultante do aumento da dimensão da empresa.',
        'uma inovação de processo que aumenta a produtividade do trabalho.',
        'um aumento do capital circulante que reduz a produtividade.',
        'uma inovação de produto que mantém a produtividade constante.'],
    c: 1,
    e: 'Um novo método de produzir é uma inovação de processo; como a produção aumenta sem mais trabalho, a produtividade do trabalho sobe. Não é uma economia de escala, porque a redução de custos resulta de uma nova tecnologia e não do aumento da dimensão da empresa; o robô é capital fixo, não circulante.' },

  { id: 'u3-14', u: 'u3',
    p: 'Contribui para o aumento da produtividade do trabalho',
    o: ['o aumento das horas de trabalho, mantendo-se a produção.',
        'a utilização de equipamentos mais antigos.',
        'a contratação de mais trabalhadores, mantendo-se a produção.',
        'a formação profissional dos trabalhadores.'],
    c: 3,
    e: 'Trabalhadores mais qualificados produzem mais por hora, o que aumenta a produtividade. Aumentar as horas ou os trabalhadores sem aumentar a produção faz, pelo contrário, diminuir a produção por unidade de trabalho.' },

  { id: 'u3-15', u: 'u3',
    p: 'Para uma padaria, constitui um custo fixo',
    o: ['a farinha utilizada no fabrico do pão.',
        'a eletricidade consumida pelos fornos.',
        'a renda mensal do estabelecimento.',
        'os sacos de papel onde o pão é vendido.'],
    c: 2,
    e: 'A renda não varia com a quantidade de pão produzida e tem de ser paga mesmo que a padaria nada produza: é um custo fixo. A farinha, a eletricidade dos fornos e os sacos aumentam quando se produz mais, sendo custos variáveis.' },

  { id: 'u3-16', u: 'u3',
    p: 'Uma empresa tem custos fixos de 2000 € e um custo variável de 3 € por unidade. Se produzir 500 unidades, o custo médio (unitário) é de',
    o: ['4 €.',
        '3 €.',
        '3500 €.',
        '7 €.'],
    c: 3,
    e: 'Custo total = 2000 + 3 × 500 = 3500 €. Custo médio = 3500 ÷ 500 = 7 €. O valor de 4 € é apenas o custo fixo médio (2000 ÷ 500) e 3 € é apenas o custo variável médio; o custo médio soma os dois.' },

  { id: 'u3-17', u: 'u3',
    p: 'Uma empresa suporta um custo total de 5000 € quando produz 200 unidades e de 5600 € quando produz 250 unidades. O custo marginal neste intervalo é de',
    o: ['12 €.',
        '22,40 €.',
        '25 €.',
        '600 €.'],
    c: 0,
    e: 'Custo marginal = variação do custo total ÷ variação da quantidade = (5600 − 5000) ÷ (250 − 200) = 600 ÷ 50 = 12 €. Os 22,40 € são o custo médio para 250 unidades (5600 ÷ 250) e os 25 € o custo médio para 200 unidades, não o custo das unidades adicionais.' },

  { id: 'u3-18', u: 'u3',
    p: 'Uma fábrica de móveis vendeu a sua produção por 180 000 €. Gastou 60 000 € em madeira, 10 000 € em eletricidade, 5000 € em tintas, 50 000 € em salários e as amortizações foram de 15 000 €. O VAB desta empresa é de',
    o: ['55 000 €.',
        '105 000 €.',
        '40 000 €.',
        '120 000 €.'],
    c: 1,
    e: 'Consumos intermédios = 60 000 + 10 000 + 5000 = 75 000 €. VAB = 180 000 − 75 000 = 105 000 €. Os salários e as amortizações não são consumos intermédios (os salários remuneram o trabalho e fazem parte do VAB), por isso subtraí-los, como nos 55 000 €, é um erro.' },

  { id: 'u3-19', u: 'u3',
    p: 'Para medir a riqueza criada pelo conjunto dos produtores de uma economia, somam-se os VAB e não os VBP porque',
    o: ['o VBP não inclui o valor dos serviços.',
        'o VAB inclui os bens produzidos no estrangeiro.',
        'a soma dos VBP contaria várias vezes o valor dos consumos intermédios.',
        'o VBP é calculado a preços diferentes dos do VAB.'],
    c: 2,
    e: 'O produto de uma empresa é, muitas vezes, consumo intermédio de outra (o trigo na farinha, a farinha no pão); somar os VBP contaria esse valor várias vezes — dupla contagem. Somando apenas o valor acrescentado em cada fase obtém-se a riqueza realmente criada. O VBP inclui serviços, pelo que essa não é a razão.' },

  { id: 'u3-20', u: 'u3',
    p: 'Uma cadeia de supermercados abre mais lojas e, por comprar em quantidades maiores, obtém melhores preços dos fornecedores, reduzindo o custo por unidade vendida. Esta situação ilustra',
    o: ['economias de escala.',
        'deseconomias de escala.',
        'um aumento do custo marginal.',
        'a terciarização da economia.'],
    c: 0,
    e: 'Economias de escala são reduções do custo médio que resultam do aumento da dimensão da empresa e da quantidade produzida ou vendida, por exemplo através de descontos em grandes compras. Haveria deseconomias de escala se o crescimento fizesse aumentar o custo médio.' },

  /* ===== Unidade 4 — Comércio e moeda ===== */
  { id: 'u4-01', u: 'u4',
    p: 'O comércio contribui para a satisfação das necessidades porque',
    o: ['transforma matérias-primas em produtos acabados.',
        'dispensa a existência de moeda nas trocas.',
        'faz chegar os bens aos consumidores no local e no momento em que deles necessitam.',
        'elimina os custos de transporte e armazenamento dos bens.'],
    c: 2,
    e: 'O comércio é uma atividade do setor terciário que aproxima a produção do consumo, acrescentando valor através do transporte, armazenamento e disponibilização dos bens. Transformar matérias-primas é uma atividade industrial (setor secundário), não comercial.' },

  { id: 'u4-02', u: 'u4',
    p: 'Um hipermercado que vende diretamente às famílias pratica comércio',
    o: ['a retalho, porque vende ao consumidor final.',
        'por grosso, porque no total vende grandes quantidades.',
        'por grosso, porque é uma grande superfície.',
        'externo, porque vende produtos importados.'],
    c: 0,
    e: 'O comércio a retalho define-se por vender ao consumidor final, em pequenas quantidades por cliente, independentemente da dimensão da loja. O grossista vende a outros comerciantes ou empresas; o volume total de vendas não é o critério.' },

  { id: 'u4-03', u: 'u4',
    p: 'Uma empresa de Aveiro vende azulejos a uma loja de decoração em Paris. Trata-se de',
    o: ['comércio interno, porque Portugal e França pertencem à União Europeia.',
        'comércio a retalho, porque o comprador é uma loja.',
        'uma importação portuguesa.',
        'comércio externo, correspondendo a uma exportação portuguesa.'],
    c: 3,
    e: 'O comércio externo envolve agentes de países diferentes; para Portugal, a venda de bens a um comprador francês é uma exportação. Pertencer à União Europeia não transforma esta transação em comércio interno do país; e, como a empresa vende a uma loja e não ao consumidor final, não se trata de comércio a retalho.' },

  { id: 'u4-04', u: 'u4',
    p: 'Uma queijaria da Serra da Estrela vende os seus queijos a um grossista, que os revende a mercearias de todo o país, onde são comprados pelos consumidores. Este percurso corresponde a um circuito de distribuição',
    o: ['direto.',
        'longo.',
        'curto.',
        'ultracurto.'],
    c: 1,
    e: 'Há dois intermediários entre o produtor e o consumidor (grossista e retalhista), o que caracteriza um circuito longo. O circuito curto tem apenas um intermediário, o retalhista; no direto, o produtor vende ao consumidor.' },

  { id: 'u4-05', u: 'u4',
    p: 'Em regra, quanto maior for o número de intermediários num circuito de distribuição,',
    o: ['menor será o preço pago pelo consumidor final.',
        'maior será o preço recebido pelo produtor.',
        'maior tende a ser a diferença entre o preço pago pelo consumidor e o recebido pelo produtor.',
        'menor será o número de serviços prestados ao longo do circuito.'],
    c: 2,
    e: 'Cada intermediário acrescenta a sua margem de comercialização, afastando o preço final do preço recebido pelo produtor. Por isso, circuitos mais longos tendem a encarecer o bem para o consumidor, e não a torná-lo mais barato, apesar dos serviços úteis que os intermediários prestam.' },

  { id: 'u4-06', u: 'u4',
    p: 'É uma vantagem do comércio eletrónico para o consumidor',
    o: ['comparar facilmente os preços de vários vendedores, a qualquer hora.',
        'poder experimentar fisicamente o produto antes de o comprar.',
        'receber o produto no próprio momento em que o encomenda.',
        'eliminar totalmente o risco de fraude nos pagamentos.'],
    c: 0,
    e: 'O comércio eletrónico está disponível 24 horas e permite comparar preços rapidamente. Não permite experimentar o produto antes da compra, obriga a esperar pela entrega e envolve riscos de fraude e de segurança dos dados, que são precisamente algumas das suas desvantagens.' },

  { id: 'u4-07', u: 'u4',
    p: 'Numa economia de troca direta, o Tomás tem batatas e quer sapatos, mas o sapateiro não quer batatas, quer peixe. A dificuldade ilustrada é',
    o: ['a indivisibilidade dos bens.',
        'a dificuldade de conservação dos bens.',
        'a ausência de uma medida comum de valor.',
        'a necessidade de dupla coincidência de necessidades.'],
    c: 3,
    e: 'Na troca direta, cada parte tem de ter aquilo que a outra quer, e vice-versa; sem essa dupla coincidência, a troca não se realiza. A falta de uma medida comum de valor é outra limitação, relacionada com a dificuldade de estabelecer quanto vale um bem em relação a outro, que não é o problema descrito.' },

  { id: 'u4-08', u: 'u4',
    p: 'Em economia, a moeda é',
    o: ['o conjunto das notas emitidas pelo banco central.',
        'tudo aquilo que é geralmente aceite como meio de pagamento.',
        'qualquer bem com valor próprio, como o ouro ou a prata.',
        'o conjunto dos ativos financeiros detidos pelas famílias.'],
    c: 1,
    e: 'O que define a moeda é a aceitação geral como meio de pagamento, e não o material de que é feita. Limitá-la às notas esquece as moedas metálicas e a moeda escritural (depósitos à ordem), que é hoje a forma de moeda mais utilizada.' },

  { id: 'u4-09', u: 'u4',
    p: 'Ao comparar o preço de dois telemóveis, um de 350 € e outro de 420 €, a Inês está a utilizar a moeda na sua função de',
    o: ['reserva de valor.',
        'intermediário geral das trocas.',
        'unidade de conta (medida de valor).',
        'meio de entesouramento.'],
    c: 2,
    e: 'A função de unidade de conta permite exprimir o valor de todos os bens na mesma unidade e compará-los. A Inês ainda não está a comprar nada, por isso a moeda não está a ser usada como intermediário das trocas.' },

  { id: 'u4-10', u: 'u4',
    p: 'O Afonso guarda todas as semanas uma parte da semanada para comprar uma bicicleta daqui a seis meses. Está a utilizar a moeda na sua função de',
    o: ['reserva de valor.',
        'unidade de conta.',
        'intermediário geral das trocas.',
        'medida de valor.'],
    c: 0,
    e: 'Guardar moeda para a gastar no futuro é usá-la como reserva de valor, transferindo poder de compra no tempo. A moeda só funcionará como intermediário das trocas no momento em que o Afonso pagar a bicicleta.' },

  { id: 'u4-11', u: 'u4',
    p: 'A função da moeda que permite ultrapassar a exigência de dupla coincidência de necessidades é a de',
    o: ['reserva de valor.',
        'unidade de conta.',
        'medida de valor.',
        'intermediário geral das trocas.'],
    c: 3,
    e: 'Como intermediário geral das trocas, a moeda divide a troca em duas operações (venda e compra): quem vende batatas recebe moeda e compra depois o que quiser, a quem quiser. A unidade de conta resolve outra limitação — a falta de uma medida comum de valor.' },

  { id: 'u4-12', u: 'u4',
    p: 'Uma subida generalizada e prolongada dos preços prejudica sobretudo a função da moeda de',
    o: ['intermediário geral das trocas.',
        'reserva de valor.',
        'unidade de conta.',
        'meio de pagamento de dívidas.'],
    c: 1,
    e: 'Se os preços sobem, a mesma quantia compra menos bens no futuro: a moeda guardada perde poder de compra, o que enfraquece a sua função de reserva de valor. A moeda continua, no entanto, a ser aceite nas trocas, pelo que a função de intermediário não é a mais afetada.' },

  { id: 'u4-13', u: 'u4',
    p: 'A sequência que traduz corretamente a evolução histórica das formas de moeda é',
    o: ['moeda metálica, moeda-mercadoria, papel-moeda, moeda escritural.',
        'moeda-mercadoria, papel-moeda, moeda metálica, moeda escritural.',
        'moeda-mercadoria, moeda metálica, papel-moeda, moeda escritural.',
        'moeda-mercadoria, moeda metálica, moeda escritural, papel-moeda.'],
    c: 2,
    e: 'A moeda evoluiu de bens com valor próprio (moeda-mercadoria) para os metais, depois para o papel-moeda e, por fim, para os depósitos bancários (moeda escritural) e a moeda eletrónica. A tendência é a desmaterialização: a moeda metálica antecede o papel-moeda, que começou por representar depósitos de metal.' },

  { id: 'u4-14', u: 'u4',
    p: 'O sal, o gado e as conchas, usados em diversas sociedades como meio de pagamento, são exemplos de',
    o: ['moeda-mercadoria.',
        'moeda fiduciária.',
        'moeda escritural.',
        'moeda divisionária.'],
    c: 0,
    e: 'A moeda-mercadoria é um bem com valor próprio, útil em si mesmo, que passa a ser geralmente aceite nas trocas. A moeda fiduciária, pelo contrário, tem um valor que assenta na confiança e não no material de que é feita.' },

  { id: 'u4-15', u: 'u4',
    p: 'As notas de euro atuais são aceites como meio de pagamento porque',
    o: ['podem ser trocadas por ouro no Banco Central Europeu.',
        'o papel de que são feitas tem um valor elevado.',
        'o seu valor corresponde ao das reservas de prata do Banco de Portugal.',
        'existe confiança na sua aceitação e têm curso legal.'],
    c: 3,
    e: 'O papel-moeda atual é inconvertível (moeda fiduciária): vale pela confiança dos agentes e porque a lei obriga à sua aceitação. A convertibilidade em ouro existiu no passado, mas foi abandonada, pelo que já não explica a aceitação das notas.' },

  { id: 'u4-16', u: 'u4',
    p: 'Constitui moeda escritural',
    o: ['o cheque preenchido para pagar uma compra.',
        'o saldo de uma conta de depósitos à ordem.',
        'uma nota de 20 € guardada numa carteira.',
        'um depósito a prazo de dois anos.'],
    c: 1,
    e: 'A moeda escritural é constituída pelos depósitos à ordem, que existem como registos nos bancos e podem ser mobilizados a qualquer momento. O cheque não é moeda: é apenas um instrumento que permite movimentar esse depósito.' },

  { id: 'u4-17', u: 'u4',
    p: 'Relativamente ao cartão de débito, é correto afirmar que',
    o: ['é uma forma de moeda metálica desmaterializada.',
        'é moeda escritural emitida pelo banco central.',
        'é um instrumento que permite movimentar moeda escritural.',
        'é um ativo com valor próprio, independente da conta bancária.'],
    c: 2,
    e: 'O cartão de débito não é moeda: permite apenas transferir a moeda escritural existente no depósito à ordem do titular. Sem saldo na conta, o cartão não serve para pagar, o que mostra que não tem valor próprio.' },

  { id: 'u4-18', u: 'u4',
    p: 'Das seguintes aplicações de poupança, a que tem maior liquidez é',
    o: ['um depósito à ordem.',
        'um depósito a prazo de dois anos.',
        'um conjunto de ações de uma empresa.',
        'um apartamento arrendado.'],
    c: 0,
    e: 'O depósito à ordem é moeda escritural e pode ser usado de imediato, sem perda de valor. O depósito a prazo exige esperar pelo vencimento ou aceitar uma penalização, as ações podem ter de ser vendidas abaixo do valor esperado e o apartamento demora muito tempo a vender.' },

  { id: 'u4-19', u: 'u4',
    p: 'A liquidez de um ativo corresponde',
    o: ['ao rendimento que esse ativo proporciona ao seu titular.',
        'ao valor de mercado desse ativo num dado momento.',
        'ao risco de esse ativo perder valor ao longo do tempo.',
        'à facilidade e rapidez com que se converte em meio de pagamento sem perda de valor.'],
    c: 3,
    e: 'A liquidez mede a rapidez e a facilidade de conversão de um ativo em moeda, sem perda de valor. Não se confunde com o valor do ativo: um imóvel pode valer muito e ter pouca liquidez, porque vendê-lo demora e pode exigir baixar o preço.' },

  { id: 'u4-20', u: 'u4',
    p: 'A água é indispensável à vida e tem um preço baixo; os diamantes têm pouca utilidade prática e um preço elevado. Este contraste mostra que',
    o: ['o preço de um bem depende apenas da sua utilidade.',
        'o preço de um bem depende não só da sua utilidade mas também da sua escassez.',
        'os bens de primeira necessidade são sempre bens livres.',
        'o valor de uso e o preço de um bem são sempre iguais.'],
    c: 1,
    e: 'O preço, expressão monetária do valor de troca, reflete a utilidade mas também a escassez do bem: a água é muito útil mas abundante, os diamantes são pouco úteis mas escassos. Se o preço dependesse apenas da utilidade, a água seria muito mais cara do que os diamantes.' }
);
