// ============================================================
// DADOS DA PLATAFORMA — Comunicação Interpessoal
// (quiz, flashcards, preenchimento, história, fofoca)
// ============================================================

// ============================================================
// DATA: 100 QUIZ QUESTIONS
// ============================================================
const quizData = [
  {q:"O que é a Comunicação Interpessoal?",o:["Envio de mensagens em massa","Troca de informação e significado entre duas ou mais pessoas","Comunicação através de tecnologia","Leitura de documentos oficiais"],a:1,e:"A Comunicação Interpessoal envolve a troca de informação, significado e emoções entre pessoas, sendo inseparável das relações humanas."},
  {q:"Segundo Minter (2010), qual é a relação entre comunicação e relações humanas?",o:["São conceitos opostos","São quase sinónimos e extremamente ligados","A comunicação é mais importante","As relações humanas dispensam comunicação"],a:1,e:"Minter (2010) afirma que os conceitos são 'quase sinónimos' e que é impossível haver relações humanas sem comunicação e vice-versa."},
  {q:"O que são os 'sinais não-verbais' na comunicação?",o:["Palavras escritas","Mensagens transmitidas sem palavras faladas (gestos, expressões, postura, toque)","Apenas o silêncio","Apenas contacto visual"],a:1,e:"Os sinais não-verbais incluem gestos, expressões faciais, postura corporal, toque, tom de voz e uso do espaço — tudo o que comunica sem palavras."},
  {q:"Qual é a Teoria da Gestão da Informação Motivada (TGIM)?",o:["Teoria sobre gestão de empresas","Teoria sobre como as pessoas gerem a incerteza e ansiedade em situações de comunicação","Teoria sobre tecnologia de informação","Teoria sobre motivação no trabalho"],a:1,e:"A TGIM explica como as pessoas gerem a incerteza e ansiedade ao comunicar, buscando informação para reduzir a incerteza."},
  {q:"O que é a Teoria dos Objetivos Múltiplos?",o:["Teoria sobre múltiplas tarefas","Teoria que explica como as pessoas perseguem vários objetivos em simultâneo na comunicação","Teoria sobre objetivos desportivos","Teoria sobre gestão de projetos"],a:1,e:"A Teoria dos Objetivos Múltiplos mostra que ao comunicar perseguimos vários objetivos em simultâneo: instrumentais, relacionais e identitários."},
  {q:"O que é o 'Perfil Verbal-Não Verbal Discrepante'?",o:["Quando se fala muito alto","Quando a mensagem verbal e não-verbal são inconsistentes/contraditórias","Quando não se usa gestos","Quando se fala e escreve ao mesmo tempo"],a:1,e:"O Perfil Discrepante ocorre quando o que dizemos verbalmente contradiz o que a nossa linguagem corporal e tom de voz transmitem."},
  {q:"O que é a Troca Social na comunicação interpessoal?",o:["Troca de dinheiro entre pessoas","Princípio de que as interações humanas envolvem trocas de recursos, recompensas e custos","Troca de redes sociais","Troca de presentes"],a:1,e:"A Troca Social é o princípio segundo o qual as interações humanas são governadas por trocas de recursos, custos e recompensas, orientadas pelo interesse próprio e reciprocidade."},
  {q:"O que distingue uma Troca Social de uma Troca Económica?",o:["A troca social envolve dinheiro, a económica não","A troca económica tem obrigações legais e precisão; a social é voluntária e baseada em confiança","São exatamente iguais","A troca social é mais formal"],a:1,e:"A troca económica envolve obrigações legais e precisão (ex: preço fixo). A troca social é voluntária, baseada em confiança, com custos e recompensas mais flexíveis."},
  {q:"O que é o Interacionismo Simbólico?",o:["Uso de símbolos matemáticos","Perspetiva que vê o comportamento social como resultado do significado que as pessoas atribuem aos símbolos","Teoria sobre sinais de trânsito","Estudo de logos e marcas"],a:1,e:"O Interacionismo Simbólico vê o comportamento social como produto dos significados simbólicos que as pessoas constroem nas interações."},
  {q:"O que afirma o Teorema de Thomas?",o:["Que a realidade é objetiva","'Se as pessoas definem as situações como reais, elas são reais nas suas consequências'","Que os símbolos são naturais","Que a comunicação é linear"],a:1,e:"O Teorema de Thomas diz que se as pessoas definem uma situação como real, ela torna-se real nas suas consequências — mostrando o poder das perceções."},
  {q:"Qual a diferença entre Ouvir e Escutar?",o:["Não há diferença","Ouvir é passivo (receção de som); Escutar é ativo (processar, interpretar e responder ao que se ouve)","Escutar é apenas para música","Ouvir requer mais esforço"],a:1,e:"Ouvir é um processo fisiológico passivo. Escutar implica atenção ativa, compreensão e resposta — é um processo cognitivo e emocional."},
  {q:"O que é a Escuta Ativa?",o:["Ouvir música com atenção","Forma de escuta em que o receptor demonstra atenção, compreensão e interesse ativo na mensagem do outro","Apenas responder com perguntas","Tomar notas durante uma conversa"],a:1,e:"A Escuta Ativa envolve prestar atenção plena, mostrar envolvimento, pedir clarificações e dar feedback — demonstrando que o outro foi compreendido."},
  {q:"O que é a Escuta Empática?",o:["Escutar apenas factos","Escutar procurando compreender os sentimentos e perspetiva do outro","Escutar para contradizer","Apenas escutar quando é obrigatório"],a:1,e:"A Escuta Empática vai além dos factos — tenta compreender a perspetiva emocional do outro, colocando-se no seu lugar."},
  {q:"Qual é uma barreira psicológica à comunicação?",o:["Ruído ambiental","Preconceitos, emoções fortes ou experiências passadas que distorcem a receção da mensagem","Falha de microfone","Língua diferente"],a:1,e:"As barreiras psicológicas incluem preconceitos, expectativas, emoções e experiências passadas que interferem na interpretação da mensagem."},
  {q:"Qual é uma barreira semântica à comunicação?",o:["Falar muito alto","Diferenças no significado atribuído às palavras ou símbolos entre emissor e recetor","Falta de iluminação","Excesso de barulho"],a:1,e:"As barreiras semânticas surgem quando os interlocutores atribuem significados diferentes às mesmas palavras, expressões ou conceitos."},
  {q:"O que é a Inteligência Emocional (IE)?",o:["A capacidade de fazer cálculos complexos","A capacidade de reconhecer, compreender e gerir as próprias emoções e as dos outros","Inteligência académica","A capacidade de reprimir emoções"],a:1,e:"A IE é a capacidade de perceber, usar, compreender e regular as emoções — tanto as próprias como as dos outros — envolvendo autoconsciência, autorregulação, motivação, empatia e competências sociais."},
  {q:"Quais são os 5 pilares da Inteligência Emocional segundo Goleman?",o:["Força, velocidade, resistência, flexibilidade, equilíbrio","Autoconsciência, autorregulação, motivação, empatia e competências sociais","Lógica, criatividade, memória, atenção, linguagem","Assertividade, passividade, agressividade, empatia, silêncio"],a:1,e:"Os 5 pilares de Goleman são: autoconsciência (conhecer as próprias emoções), autorregulação, motivação interna, empatia e competências sociais."},
  {q:"O que é a IE de 'habilidade' (ability)?",o:["A capacidade de realizar tarefas manuais","Um conjunto de capacidades cognitivas sobre emoções: perceber, usar, compreender e regular emoções","A tendência para expressar emoções","A capacidade de ignorar emoções"],a:1,e:"A IE de habilidade envolve capacidades cognitivas mensuráveis: perceber emoções nos outros, usá-las para pensar, compreendê-las e regulá-las adaptativamente."},
  {q:"O que é a IE de 'traço' (trait)?",o:["Um traço físico observável","Traços auto-reportados relacionados com autoeficácia emocional, bem-estar e sociabilidade","A habilidade de calcular emoções","Traços exclusivamente genéticos"],a:1,e:"A IE de traço refere-se a como a pessoa percebe as suas próprias características emocionais — é auto-reportada e inclui bem-estar subjetivo e autoeficácia emocional."},
  {q:"O que é a Teoria da Atribuição no contexto da IE?",o:["Teoria sobre atribuição de tarefas no trabalho","Processo pelo qual interpretamos as causas do comportamento dos outros (interno vs externo)","Teoria sobre distribuição de recursos","Processo de atribuição de notas"],a:1,e:"A Teoria da Atribuição explica como interpretamos as causas do comportamento alheio — atribuindo causas internas (personalidade) ou externas (situação), o que afeta como comunicamos."},
  {q:"O que é a Teoria da Troca Afetiva?",o:["Troca de presentes em relações afetivas","Como as emoções trocadas nas interações influenciam e regulam as relações interpessoais","Teoria sobre mercados emocionais","Troca de informação racional"],a:1,e:"A Teoria da Troca Afetiva explica como as emoções que transmitimos e recebemos nas interações moldam e regulam a qualidade das nossas relações."},
  {q:"Como se caracteriza o estilo de comunicação Assertivo?",o:["Impõe a sua vontade ignorando os outros","Expressa necessidades e opiniões com respeito pelos direitos próprios e dos outros","Evita sempre o conflito","Usa ironia e sarcasmo para comunicar"],a:1,e:"O assertivo defende os seus direitos construtivamente, é direto, honesto e específico, e respeita os direitos dos outros — o estilo mais adaptativo."},
  {q:"Como se caracteriza o estilo de comunicação Passivo?",o:["Expressa as suas opiniões com confiança","Evita o conflito, sublima as suas necessidades e cede facilmente quando desafiado","Impõe as suas necessidades","Usa manipulação indireta"],a:1,e:"O passivo evita conflito, teme a desaprovação, hesita antes de responder e suprime as suas necessidades para satisfazer os outros."},
  {q:"Como se caracteriza o estilo de comunicação Agressivo?",o:["Respeita as opiniões dos outros","Procura alcançar objetivos atacando, ameaçando ou intimidando os outros","Evita confrontos a todo o custo","Comunica de forma indireta"],a:1,e:"O agressivo procura os seus objetivos às custas dos outros, usa ameaças, ataques pessoais, é sarcástico e não coopera — 'eu venço, tu perdes'."},
  {q:"O que distingue o estilo Passivo-Agressivo?",o:["Combina agressividade física com passividade verbal","Evita confronto direto mas manifesta insatisfação de forma indireta (ironia, sabotagem velada)","É uma versão moderada do assertivo","É o estilo mais eficaz"],a:1,e:"O passivo-agressivo evita o confronto direto mas expressa insatisfação indiretamente através de ironia, ambiguidade ou sabotagem velada."},
  {q:"Porque é o estilo assertivo considerado o mais desejável?",o:["Porque garante sempre ganhar conflitos","Porque equilibra defesa dos próprios direitos com respeito pelos outros, contribuindo para relações saudáveis","Porque é o mais passivo","Porque nunca cria conflito"],a:1,e:"A assertividade é desejável porque defende os direitos próprios sem violar os dos outros, promove comunicação aberta e contribui para maior satisfação pessoal e relacional."},
  {q:"O que é o Modelo DESC na comunicação assertiva?",o:["Modelo de defesa, escuta, síntese e conclusão","Estrutura: Descreve → Expressa → Sugere → Consequências — para comunicar assertivamente em situações de conflito","Modelo de desenvolvimento estratégico de competências","Modelo de decisão empresarial"],a:1,e:"O DESC é uma estrutura para comunicação assertiva: Descreve o comportamento problemático, Expressa como te sentes, Sugere uma mudança, e indica as Consequências positivas."},
  {q:"O que é o Modelo XYZ?",o:["Modelo matemático","Estrutura de comunicação: 'Quando X, sinto Y, porque Z' — para expressar sentimentos de forma não acusatória","Modelo de gestão de projetos","Modelo de análise de dados"],a:1,e:"O Modelo XYZ permite expressar sentimentos sem atacar o outro: 'Quando fazes X, sinto Y, porque Z' — foca no comportamento e não na pessoa."},
  {q:"O que é a Teoria da Retórica Normativa (TRN)?",o:["Teoria sobre normas gramaticais","Teoria que estuda os princípios éticos da persuasão na comunicação","Teoria sobre retórica política","Teoria sobre normas de pronunciação"],a:1,e:"A TRN, baseada em Aristóteles, estuda os princípios éticos da persuasão — como comunicar de forma eficaz e justa, respeitando o receptor."},
  {q:"O que é o Ethos na retórica?",o:["Apelo às emoções do público","Credibilidade e integridade do comunicador que leva o público a confiar na mensagem","Uso de argumentos lógicos","Estrutura do discurso"],a:1,e:"Ethos é a credibilidade do orador — a perceção de integridade, competência e confiabilidade que leva o público a aceitar a mensagem."},
  {q:"O que é o Logos na retórica?",o:["Apelo emocional","Uso de argumentos racionais, lógicos e evidências para convencer","A credibilidade do orador","A narrativa pessoal do orador"],a:1,e:"Logos refere-se ao uso de argumentos racionais, dados, provas e lógica para persuadir — o apelo à razão do público."},
  {q:"O que é o Pathos na retórica?",o:["A credibilidade do orador","Apelo às emoções do público para envolver e persuadir","Uso de dados estatísticos","A estrutura lógica do argumento"],a:1,e:"Pathos é o apelo emocional — ativar as emoções do público (medo, esperança, empatia) para tornar a mensagem mais persuasiva."},
  {q:"Segundo a TRN, como deve ser usado o Pathos eticamente?",o:["Pode manipular livremente as emoções","Deve ser usado respeitando a capacidade crítica do público, sem manipulação emocional","Deve ser evitado completamente","Deve ser usado apenas em discursos políticos"],a:1,e:"A TRN defende que o apelo emocional deve ser ético — pode envolver emoções mas não deve manipular, distorcer ou explorar vulnerabilidades do público."},
  {q:"O que são os 'relacionamentos' segundo Watzlawick?",o:["Apenas amizades formais","Emergem da interação entre pessoas com regras estabelecidas e aceites por ambas as partes","Contratos legais entre pessoas","Apenas relações familiares"],a:1,e:"Para Watzlawick, os relacionamentos emergem da interação com regras comunicativas aceites por ambas as partes, regulando os comportamentos."},
  {q:"O que é a 'Expressividade' na comunicação não-verbal?",o:["Volume da voz","Grau de abertura e visibilidade das emoções que o comunicador projeta através de sinais não-verbais","Habilidade de escrever expressivamente","Uso de palavras expressivas"],a:1,e:"A Expressividade é a intensidade com que as emoções são projetadas através de sinais não-verbais — movimentos, microexpressões, tom de voz."},
  {q:"O que é a 'Capacidade de Resposta' na comunicação?",o:["Velocidade de digitação","Habilidade de perceber e responder adequadamente às necessidades e sinais comunicativos do interlocutor","Capacidade de falar alto","Tempo de resposta a e-mails"],a:1,e:"A Capacidade de Resposta é a habilidade de 'ler' os sinais do outro e ajustar a própria comunicação de forma adaptativa e oportuna."},
  {q:"Por que são importantes os silêncios na comunicação interpessoal?",o:["Porque significam falta de interesse","São elementos fundamentais que fazem parte da comunicação, criam espaço para escuta e transmitem emoções","Devem ser sempre evitados","São apenas pausas sem significado"],a:1,e:"Os silêncios são fundamentais: fazem parte integrante da comunicação, são muito frequentes, podem ser embaraçosos ou profundos, e são necessários para escutar o outro."},
  {q:"O que é a 'interdependência' nas relações interpessoais?",o:["Dependência financeira","Os resultados de cada pessoa são influenciados pelos esforços dos outros — os resultados são partilhados","Independência total entre pessoas","Dependência emocional"],a:1,e:"Interdependência significa que numa relação os resultados de cada um são influenciados pelo outro — o sucesso individual depende dos esforços do parceiro."},
  {q:"O que é a 'equidade' nas trocas sociais?",o:["Igualdade absoluta de recursos","Perceção de que os custos e benefícios são distribuídos de forma justa na relação","Ausência de conflito","Partilha igual de responsabilidades"],a:1,e:"A equidade é a perceção de justiça na distribuição de custos e benefícios numa relação — não significa igualdade perfeita mas proporcionalidade percebida."},
  {q:"O que é a 'reciprocidade' na troca social?",o:["Dar sempre o mesmo que se recebe em dinheiro","Princípio de que as trocas devem ser mutuamente benéficas e que as ações dos outros geram expectativas de retorno","Evitar qualquer troca","Apenas troca de favores formais"],a:1,e:"A reciprocidade é o princípio de que as trocas nas relações devem ter retorno — quando alguém nos dá algo, sentimos necessidade de retribuir."},
  {q:"O que é o 'interesse próprio' (self-interest) na troca social?",o:["Egoísmo puro","O ímpeto pelo qual as pessoas agem de acordo com os seus resultados percebidos e projetados nas interações","Apenas motivações financeiras","Comportamento altruísta"],a:1,e:"O interesse próprio é a motivação para agir de acordo com os resultados esperados de cada interação — não é necessariamente egoísta, pois pode incluir cooperação."},
  {q:"Qual é a definição de assertividade segundo Alberti & Emmons (2017)?",o:["Impor a vontade sobre os outros","Expressão direta, honesta e respeitosa de pensamentos e sentimentos","Evitar conflito a todo o custo","Usar persuasão intensa"],a:1,e:"Alberti & Emmons definem assertividade como 'expressão direta, honesta e respeitosa de pensamentos e sentimentos', equilibrando auto-expressão com respeito pelo outro."},
  {q:"Quais são os benefícios da assertividade segundo a investigação?",o:["Aumento de conflitos","Relações equilibradas, redução de stress e maior capacidade de resolução de problemas","Isolamento social","Maior dominância nas relações"],a:1,e:"Estudos mostram que a assertividade está ligada a relações mais equilibradas, menor stress, maior satisfação profissional e melhor resolução de conflitos (Speed et al., 2018)."},
  {q:"O que é a IE 'mista' (competências)?",o:["Combinação de IE de habilidade e de traço","Competências comportamentais aplicadas ao desempenho social (consciência de si, autorregulação, motivação, empatia, competências sociais)","Um tipo de IE indefinido","IE que combina emoções e lógica"],a:1,e:"A IE mista refere-se a competências emocionais comportamentais observáveis — como dar feedback, gerir conflitos ou demonstrar empatia em contextos sociais e profissionais."},
  {q:"Como a IE de habilidade afeta a comunicação?",o:["Não afeta a comunicação","Melhora a precisão ao descodificar expressões e voz, e melhora o 'timing' comunicativo","Aumenta a agressividade","Reduz a necessidade de comunicar"],a:1,e:"A IE de habilidade permite ler com mais precisão as expressões faciais e tom de voz dos outros, e ter melhor 'timing' — saber quando e como dizer as coisas."},
  {q:"O que é a 'autoconsciência' como pilar da IE?",o:["Saber fazer auto-retratos","A capacidade de reconhecer e compreender as próprias emoções, forças e limitações","Vigilância constante dos outros","Consciência do ambiente físico"],a:1,e:"A autoconsciência é o primeiro pilar da IE de Goleman — a capacidade de reconhecer as próprias emoções no momento em que ocorrem e compreender como afetam o comportamento."},
  {q:"O que é a 'autorregulação' como pilar da IE?",o:["Disciplina física","A capacidade de controlar emoções destrutivas e impulsos, e adaptar-se a circunstâncias em mudança","Regulação de temperatura corporal","Autocontrolo alimentar"],a:1,e:"A autorregulação é a capacidade de gerir as próprias emoções e impulsos — não os suprimir, mas expressá-los de forma adequada e adaptativa."},
  {q:"O que é a 'empatia' como pilar da IE?",o:["Simpatia superficial","A capacidade de compreender as emoções dos outros e responder de forma adequada","Leitura do pensamento","Imitação das emoções dos outros"],a:1,e:"A empatia é a capacidade de perceber e compreender os sentimentos e perspetivas dos outros — colocarmo-nos no lugar deles para responder adequadamente."},
  {q:"Que tipo de comportamento não-verbal caracteriza o comunicador assertivo?",o:["Olhar desafiante e gestos ameaçadores","Voz firme e calma, contacto visual sem intimidar, expressão facial aberta e postura descontraída","Desviar o olhar, fala fraca e hesitante","Interrupções frequentes e tom agressivo"],a:1,e:"O assertivo tem voz firme mas calma, mantém contacto visual sem intimidar, tem expressão facial aberta e postura descontraída — transmite confiança sem agressividade."},
  {q:"Que tipo de comportamento não-verbal caracteriza o comunicador passivo?",o:["Postura dominante e voz forte","Desvia o olhar, postura retraída, voz fraca ou lamurienta, sorriso forçado","Expressão facial agressiva","Interrompe frequentemente"],a:1,e:"O passivo desvia o olhar, tem postura retraída, fala com voz fraca ou hesitante e sorri de forma forçada — sinais de insegurança e submissão."},
  {q:"O que é a 'Teoria da Retórica Normativa' especificamente?",o:["Uma teoria sobre gramática normativa","Uma teoria que combina princípios clássicos de persuasão com ética comunicativa","Uma teoria sobre leis de comunicação","Uma teoria sobre normas sociais"],a:1,e:"A TRN combina os princípios clássicos de Aristóteles com preocupações éticas modernas — como persuadir de forma eficaz, honesta e respeitosa."},
  {q:"Que papel tem a 'credibilidade' na persuasão eficaz?",o:["Não é relevante para a persuasão","O público confia mais em comunicadores que percebe como credíveis e íntegros (Ethos)","Só é relevante em contextos académicos","A credibilidade pode ser fabricada facilmente"],a:1,e:"A credibilidade (Ethos) é fundamental — quando o público percebe o comunicador como competente e honesto, está mais disposto a aceitar a mensagem."},
  {q:"O que é a 'comunicação contemporânea' e os seus desafios?",o:["Comunicação por carta","Comunicação na era digital — marcada por excesso de informação, velocidade, filtros algorítmicos e questões de autenticidade","Comunicação apenas face a face","Comunicação sem tecnologia"],a:1,e:"A comunicação contemporânea enfrenta desafios como sobrecarga informacional, velocidade das interações digitais, questões de autenticidade e influência do contexto cultural."},
  {q:"O que é a 'autenticidade' na comunicação contemporânea?",o:["Dizer sempre o que pensamos sem filtros","A correspondência genuína entre o que se sente interiormente e o que se expressa — comunicar de forma verdadeira","Comunicar apenas factos verificáveis","Evitar qualquer tipo de persuasão"],a:1,e:"A autenticidade é a congruência entre o estado interno e a expressão externa — comunicar de forma genuína, sem máscaras ou performatividade excessiva."},
  {q:"Como a Cultura afeta a Comunicação Interpessoal?",o:["Não tem qualquer influência","Molda os padrões de comunicação, os valores, as normas de proximidade, de contacto visual e de expressão emocional","Apenas afeta a língua falada","Afeta apenas a comunicação formal"],a:1,e:"A cultura influencia profundamente como comunicamos — desde regras de contacto visual e toque, ao estilo de negociação, à expressão de emoções e ao uso do silêncio."},
  {q:"O que é a 'motivação' como pilar da IE de Goleman?",o:["Motivação financeira","Impulso interno para alcançar objetivos com entusiasmo e persistência, independentemente de recompensas externas","Motivação dada por outros","Motivação para evitar emoções"],a:1,e:"A motivação intrínseca é a paixão interna pelo trabalho — não movida por dinheiro ou status, mas por satisfação e crescimento pessoal — um pilar da IE de Goleman."},
  {q:"O que é a 'competência social' como pilar da IE?",o:["Habilidade de trabalhar sozinho","Capacidade de gerir relações, inspirar e influenciar os outros e construir redes de contacto","Habilidade de memorizar nomes","Competência técnica"],a:1,e:"A competência social é a capacidade de gerir relações interpessoais com eficácia — persuadir, liderar, construir redes e gerir conflitos construtivamente."},
  {q:"Porque é que 'é impossível não comunicar' (Watzlawick)?",o:["Porque todos falam constantemente","Porque mesmo o silêncio e a inação transmitem mensagens nas relações interpessoais","Porque a comunicação é automática","Porque os humanos comunicam 24h por dia"],a:1,e:"Watzlawick afirma que 'é impossível não comunicar' — mesmo o silêncio, a ausência ou a inação são formas de mensagem nas interações interpessoais."},
  {q:"O que são as 'Competências Sociais' no contexto da IE?",o:["Etiqueta social formal","Conjunto de habilidades para gerir relações com eficácia: comunicação, liderança, resolução de conflitos, trabalho em equipa","Apenas habilidades de networking","Capacidade de memorizar nomes"],a:1,e:"As competências sociais da IE incluem habilidades relacionais: comunicar com clareza, liderar, inspirar mudança, gerir conflitos e construir equipas colaborativas."},
  {q:"Qual é o objetivo do Modelo DESC?",o:["Descrever emoções de forma vaga","Estruturar a comunicação assertiva para resolver conflitos de forma construtiva, sem atacar a pessoa","Evitar conversas difíceis","Impor soluções aos outros"],a:1,e:"O DESC oferece uma estrutura para abordar situações difíceis de forma assertiva: descrevendo o comportamento, expressando sentimentos, sugerindo mudança e mostrando as consequências."},
  {q:"Qual é a diferença entre 'comunicação de alta contexto' e 'baixo contexto'?",o:["Alta contexto usa mais tecnologia","Alta contexto usa muito contexto implícito (cultura asiática); baixo contexto é mais direto e explícito (cultura ocidental)","Não há diferença real","Alta contexto é mais ruidosa"],a:1,e:"Culturas de alto contexto (ex: japonesa) comunicam muito através de contexto implícito, relações e não-verbal. Culturas de baixo contexto (ex: americana) são mais diretas e explícitas."},
  {q:"O que são as 'barreiras fisiológicas/ambientais' à comunicação?",o:["Preconceitos pessoais","Obstáculos físicos como ruído, temperatura, distância, ou limitações sensoriais do receptor","Diferenças de idioma","Emoções negativas"],a:1,e:"As barreiras fisiológicas incluem surdez, fadiga, dor; as ambientais incluem ruído, iluminação inadequada, distância ou distrações físicas no ambiente."},
  {q:"O que é a 'Escuta Reflexiva'?",o:["Escutar enquanto se olha ao espelho","Técnica de escuta em que se reformula e reflete de volta o que o outro disse para confirmar compreensão","Escutar de forma passiva","Escutar apenas factos objetivos"],a:1,e:"A escuta reflexiva envolve parafrasear ou reformular o que o outro disse — 'Então o que estás a dizer é...' — para confirmar compreensão e mostrar atenção."},
  {q:"Como os 'preconceitos' afetam a escuta?",o:["Não têm impacto na escuta","Filtram e distorcem a mensagem recebida — ouvimos o que esperamos ouvir e ignoramos o que contraria as nossas crenças","Melhoram a compreensão","Só afetam a comunicação escrita"],a:1,e:"Os preconceitos são barreiras psicológicas que fazem com que filtremos as mensagens — tendemos a ouvir o que confirma as nossas crenças (confirmação cognitiva)."},
  {q:"Qual é a função do 'feedback' na comunicação interpessoal?",o:["Avaliar o desempenho académico","Resposta do recetor que informa o emissor sobre como a mensagem foi recebida e compreendida","Apenas criticar o comunicador","Finalizar a conversa"],a:1,e:"O feedback é a resposta do recetor que fecha o ciclo comunicativo — informa o emissor se a mensagem foi recebida, compreendida e que efeito produziu."},
  {q:"O que é a 'proxémica' na comunicação não-verbal?",o:["Estudo de expressões faciais","Estudo do uso e perceção do espaço físico nas interações (distância íntima, pessoal, social, pública)","Estudo do toque","Estudo do olhar"],a:1,e:"A proxémica (Hall) estuda como usamos o espaço nas interações — distância íntima (~45cm), pessoal (~120cm), social (~360cm) e pública (+360cm)."},
  {q:"O que é a 'cinésica' na comunicação não-verbal?",o:["Estudo do espaço","Estudo dos movimentos corporais — gestos, postura, expressões faciais, contacto visual","Estudo do tempo","Estudo da voz"],a:1,e:"A cinésica (Birdwhistell) é o estudo dos movimentos corporais como forma de comunicação — gestos, postura, expressões faciais, olhar e orientação do corpo."},
  {q:"O que é a 'paralinguagem' na comunicação?",o:["Idioma paralelo","Elementos vocais que acompanham as palavras: tom, ritmo, volume, pausas, entonação, timbre","Linguagem de sinais","Segunda língua aprendida"],a:1,e:"A paralinguagem são os elementos vocais além das palavras — como dizemos algo: tom, volume, ritmo, pausas e entonação que modificam o significado da mensagem."},
  {q:"Qual é a importância do 'toque' nas relações interpessoais?",o:["Não tem importância","É através do contacto físico que se transmitem sentimentos e se desencadeiam reações positivas ou negativas","Deve ser sempre evitado","Só é relevante em relações românticas"],a:1,e:"O toque é uma forma poderosa de comunicação não-verbal — transmite afeto, apoio, poder ou dominância, e desencadeia reações emocionais fortes."},
  {q:"Como o 'tempo' funciona como forma de comunicação?",o:["O tempo não comunica nada","A forma como gerimos o tempo — pontualidade, duração, silêncios — transmite mensagens sobre respeito, prioridades e status","Apenas em contextos formais","Apenas em culturas ocidentais"],a:1,e:"A 'cronémica' estuda o tempo como comunicação — chegar tarde comunica desrespeito; o tempo que dedicamos a alguém comunica a sua importância para nós."},
  {q:"O que é a 'distância íntima' na proxémica?",o:["Distância entre países","Zona reservada para relações íntimas (~0-45cm) onde a comunicação é muito pessoal e envolve toque","Distância entre colegas de trabalho","Distância em palcos públicos"],a:1,e:"A distância íntima (~0-45cm) é a zona mais privada, reservada para relações muito próximas — permite toque, sussurros e comunicação muito pessoal."},
  {q:"O que são 'microexpressões' faciais?",o:["Expressões muito exageradas","Expressões emocionais faciais brevíssimas (menos de 0.5 segundos) que revelam emoções genuínas","Expressões teatrais","Expressões aprendidas culturalmente"],a:1,e:"As microexpressões são flashes emocionais faciais involuntários — duram menos de 0.5 segundos e revelam emoções genuínas que tentamos esconder."},
  {q:"O que é o 'ruído semântico' na comunicação?",o:["Barulho físico no ambiente","Interferência causada por diferenças no significado atribuído às palavras entre interlocutores","Ruído em chamadas telefónicas","Erros de gramática"],a:1,e:"O ruído semântico surge quando emissor e receptor atribuem significados diferentes às mesmas palavras — criando mal-entendidos apesar da transmissão técnica ser perfeita."},
  {q:"Como a assertividade contribui para a resolução de conflitos?",o:["Elimina todos os conflitos","Permite expressar perspetivas diretamente e ouvir as do outro, criando condições para soluções mutuamente satisfatórias","Determina quem ganha o conflito","Evita que os conflitos sejam discutidos"],a:1,e:"A assertividade cria condições para resolver conflitos construtivamente — permite expressar as próprias necessidades claramente e ouvir as do outro, procurando soluções 'eu venço, tu também venço'."},
  {q:"Qual é o papel da 'empatia' na escuta ativa?",o:["A empatia não está relacionada com a escuta","A empatia permite compreender a perspetiva emocional do outro, tornando a escuta mais profunda e a resposta mais adequada","A empatia apenas serve para simpatizar","A empatia distorce a escuta objetiva"],a:1,e:"A empatia é central na escuta ativa — permite ir além das palavras e compreender os sentimentos e necessidades do outro, respondendo de forma mais eficaz."},
  {q:"O que é a 'metacomunicação'?",o:["Comunicação sobre comunicação","Comunicar sobre a própria comunicação — reflexão explícita sobre o processo comunicativo em curso","Comunicação através de metáforas","Comunicação de massas"],a:1,e:"A metacomunicação é comunicar sobre o próprio processo de comunicação — 'Acho que não me estou a fazer entender' é metacomunicação, uma forma de regular a interação."},
  {q:"O que são 'barreiras tecnológicas' à comunicação?",o:["Falta de interesse em tecnologia","Interferências causadas por tecnologia: falhas de ligação, notificações, desumanização das interações digitais, perda de sinais não-verbais","Excesso de tecnologia avançada","Apenas problemas de hardware"],a:1,e:"As barreiras tecnológicas incluem falhas de ligação, ausência de sinais não-verbais em comunicação digital, distrações de notificações e a desumanização de algumas formas de comunicação mediada."},
  {q:"Qual é a diferença entre 'simpatia' e 'empatia'?",o:["Não há diferença real","Simpatia é sentir compaixão por alguém; empatia é colocar-se no lugar do outro e compreender a sua perspetiva emocional","Empatia é mais superficial","Simpatia requer mais esforço"],a:1,e:"Simpatia é reconhecer o sofrimento do outro de fora. Empatia é entrar na perspetiva do outro — compreender como se sente a partir de dentro, sem julgamento."},
  {q:"Que papel desempenha o 'contexto' na comunicação interpessoal?",o:["O contexto não afeta a comunicação","O contexto (físico, social, cultural, temporal) molda o significado das mensagens e as expectativas dos interlocutores","O contexto só importa em negócios","O contexto apenas afeta a língua usada"],a:1,e:"O contexto é fundamental — uma mesma mensagem tem significados diferentes conforme o contexto físico, social, cultural e temporal em que é produzida."},
  {q:"O que é a 'Teoria dos Papéis' nas relações interpessoais?",o:["Teoria teatral","Conceito de que nas relações todos desempenhamos 'papéis' sociais com expectativas de comportamento associadas","Teoria de gestão empresarial","Teoria sobre papéis de género"],a:1,e:"A Teoria dos Papéis afirma que nas interações sociais desempenhamos papéis com comportamentos esperados — pai, aluno, líder — e que a violação desses papéis cria conflito."},
  {q:"O que significa 'maximizar resultados' na Troca Social?",o:["Ganhar sempre mais dinheiro","Tentar obter o máximo benefício das interações, às vezes mas nem sempre em prejuízo dos outros","Trabalhar o máximo de horas","Maximizar o número de relações"],a:1,e:"Na Troca Social, as pessoas tendem a maximizar resultados — procurar o máximo benefício. Mas cooperar pode ser estrategicamente mais vantajoso do que competir."},
  {q:"Como a IE contribui para a liderança eficaz?",o:["A IE é irrelevante para a liderança","Líderes com alta IE motivam melhor, gerem conflitos com mais eficácia, criam equipas mais coesas e inspiram confiança","A IE diminui a autoridade do líder","Apenas a inteligência cognitiva importa na liderança"],a:1,e:"A investigação mostra que a IE é um preditor-chave do sucesso na liderança — líderes emocionalmente inteligentes criam climas positivos, motivam equipas e gerem conflitos construtivamente."},
  {q:"O que é o 'princípio da cooperação' de Grice?",o:["Cooperar em todas as decisões","Princípio de que os interlocutores cooperam implicitamente para tornar a comunicação eficaz — sendo relevantes, verdadeiros e claros","Acordo contratual de cooperação","Cooperação em jogos"],a:1,e:"Grice propôs que a comunicação eficaz se baseia numa cooperação implícita — ser tão informativo quanto necessário, verdadeiro, relevante e claro (máximas de Grice)."},
  {q:"Que comportamento verbal caracteriza o comunicador passivo?",o:["Usa linguagem direta e clara","Usa termos hesitantes ('talvez', 'não sei bem'), dá respostas longas com pedidos de desculpa, cede facilmente","Usa ameaças implícitas","Usa sarcasmo frequente"],a:1,e:"O comunicador passivo hesita antes de responder, usa muitas qualificações ('talvez', 'acha que sim?'), pede muitas desculpas e cede facilmente quando desafiado."},
  {q:"Qual é o papel das 'normas de comunicação' nas relações?",o:["São apenas leis formais","Regras implícitas ou explícitas aceites pelos interlocutores que regulam quem fala, como, quando e sobre o quê","São apenas relevantes em contextos profissionais","Normas que nunca mudam"],a:1,e:"As normas de comunicação são regras implícitas ou explícitas que estruturam as interações — quem fala, em que ordem, que tópicos são adequados, como se exprime discordância."},
  {q:"O que é a 'autoconsciência' como primeiro pilar da IE de Goleman e por que razão é considerada a base de todos os outros?",o:["É a capacidade de estar atento ao ambiente externo","É a capacidade de reconhecer as próprias emoções no momento em que ocorrem e compreender como afetam pensamentos e comportamento — base de todos os outros pilares","É a consciência das emoções dos outros","É exclusivamente a capacidade de introspecção filosófica"],a:1,e:"A autoconsciência é o ponto de partida da IE: sem reconhecer as nossas próprias emoções em tempo real, não podemos regulá-las (autorregulação), nem motivarmo-nos genuinamente, nem ser empáticos. É a fundação de todos os outros pilares."},
  {q:"De que forma a 'Teoria dos Objetivos Múltiplos' explica conflitos aparentemente triviais nas relações interpessoais?",o:["Diz que os conflitos surgem sempre por razões financeiras","Mostra que quando os objetivos instrumentais, relacionais e identitários de duas pessoas entram em colisão, mesmo uma conversa simples pode escalar para conflito","Afirma que os conflitos são sempre intencionais","Explica que conflitos só surgem em comunicação verbal"],a:1,e:"A Teoria dos Objetivos Múltiplos revela que em cada interação perseguimos objetivos simultâneos — obter um resultado (instrumental), preservar a relação (relacional) e proteger a nossa imagem (identitário). Quando estes objetivos colidem com os do outro, surgem conflitos mesmo em situações aparentemente simples."},
  {q:"O que é a 'identificação' na retórica de Kenneth Burke?",o:["Identificar o público-alvo","Processo de estabelecer pontos de ligação e semelhança com o público para tornar a persuasão mais eficaz","Identificar argumentos falaciosos","Identificar a intenção do orador"],a:1,e:"Burke propôs que a persuasão eficaz começa com 'identificação' — o orador estabelece pontos de ligação e semelhança com o público, reduzindo a distância e aumentando a recetividade."},
  {q:"O que é a 'dissonância cognitiva' na comunicação interpessoal?",o:["Ruído cognitivo","Desconforto psicológico causado por informações contraditórias que o receptor tenta resolver — pode levar à rejeição de mensagens","Excesso de informação","Conflito de opiniões"],a:1,e:"A dissonância cognitiva é o desconforto de ter crenças contraditórias — ao comunicar, as pessoas frequentemente rejeitam informação que contradiz as suas crenças para reduzir esse desconforto."},
  {q:"Qual é a relação entre 'perceção' e 'comunicação'?",o:["A perceção não afeta a comunicação","A perceção filtro a realidade — vemos e ouvimos o que esperamos, o que afeta como interpretamos as mensagens dos outros","A perceção é objetiva","A perceção só afeta a comunicação escrita"],a:1,e:"A perceção é o filtro pelo qual interpretamos as mensagens — as nossas expectativas, experiências e estado emocional moldam o que 'vemos' e 'ouvimos' nas interações."},
  {q:"O que significa 'comunicar eficazmente' na prática?",o:["Falar muito e rapidamente","Conseguir que a mensagem pretendida seja recebida e compreendida como pretendido, produzindo o efeito desejado na relação","Usar vocabulário elaborado","Nunca criar conflito"],a:1,e:"A comunicação eficaz ocorre quando a mensagem intencionada é recebida e compreendida como pretendido — considerando o contexto, o receptor e a relação."},
  {q:"Qual é o problema da 'comunicação unilateral'?",o:["É muito eficiente","Ignora o feedback do receptor, não permite ajuste da mensagem e prejudica a relação interpessoal","É o método mais eficaz","Apenas funciona em contextos formais"],a:1,e:"A comunicação unilateral (sem feedback) não permite verificar se a mensagem foi compreendida, não cria diálogo e prejudica as relações interpessoais pela falta de reciprocidade."},
  {q:"Que papel tem a 'motivação' na gestão da informação (TGIM)?",o:["A motivação não tem papel","A motivação determina que tipo de informação as pessoas procuram para gerir a incerteza e a ansiedade em interações","Apenas motiva a comunicar mais","Motiva a evitar comunicação"],a:1,e:"Na TGIM, a motivação determina como as pessoas gerem a incerteza — dependendo do nível de ansiedade e incerteza, podem procurar ou evitar informação para regular o seu estado."},
  {q:"O que distingue a comunicação 'pública' da 'interpessoal'?",o:["Apenas o número de pessoas","A comunicação pública é unidirecional e formal; a interpessoal é bidirecional, pessoal e baseada em relação","A comunicação pública usa microfones","A interpessoal é apenas cara-a-cara"],a:1,e:"A comunicação interpessoal é íntima, bidirecional e moldada pela relação — ao contrário da pública, que é mais formal, unidirecional e não depende de relação pessoal."},
  {q:"O que é a 'gestão de impressões' na comunicação?",o:["Gerir a reputação empresarial","O processo pelo qual as pessoas controlam conscientemente a informação que transmitem para influenciar como são percebidas pelos outros","Impressão de documentos","Gestão de fotografias"],a:1,e:"A gestão de impressões (Goffman) é o processo pelo qual gerimos a nossa 'apresentação' para controlar como os outros nos percebem — escolhendo roupa, palavras, postura."},
  {q:"O que é a 'janela de Johari'?",o:["Um tipo de janela arquitetónica","Modelo que representa os níveis de autoconhecimento e comunicação: o que é conhecido/desconhecido por si mesmo e pelos outros","Um modelo de negociação","Um modelo de gestão de conflitos"],a:1,e:"A Janela de Johari divide o autoconhecimento em 4 quadrantes: Arena (conhecido por mim e pelos outros), Ponto Cego (desconhecido por mim, conhecido pelos outros), Fachada (conhecido por mim, desconhecido pelos outros) e Desconhecido."},
  {q:"Como os 'desafios digitais' afetam a autenticidade comunicativa?",o:["A tecnologia não afeta a autenticidade","A comunicação digital facilita a curadoria e performance da identidade, podendo criar distância entre a persona apresentada e o eu autêntico","A tecnologia sempre aumenta a autenticidade","A autenticidade é mais fácil online"],a:1,e:"As redes sociais e comunicação digital permitem construir personas cuidadosamente editadas — criando tensão entre a 'performance' online e a autenticidade das relações interpessoais reais."},
  {q:"O que é a 'comunicação não-violenta' (CNV)?",o:["Comunicar sem usar palavras fortes","Abordagem de comunicação focada em observações, sentimentos, necessidades e pedidos concretos — sem julgamentos ou críticas pessoais","Comunicar em voz baixa","Evitar toda a forma de conflito"],a:1,e:"A CNV (Rosenberg) propõe comunicar através de: Observações (não julgamentos), Sentimentos, Necessidades e Pedidos concretos — criando ligação genuína sem violência verbal."},
  {q:"Qual é a relação entre 'locus de controlo' e comunicação assertiva?",o:["Não há relação","Pessoas com locus de controlo interno (creem que controlam os seus resultados) tendem a ser mais assertivas e eficazes comunicativamente","Locus externo facilita assertividade","O locus de controlo é irrelevante"],a:1,e:"O locus de controlo interno — a crença de que controlamos os nossos resultados — está associado a maior assertividade, pois a pessoa acredita que a sua comunicação pode fazer diferença."},
  {q:"O que é a 'competência comunicativa'?",o:["Apenas ter boas notas em língua portuguesa","A capacidade de comunicar de forma eficaz e adequada em diferentes contextos, relações e situações culturais","Falar muitas línguas","Ter vocabulário extenso"],a:1,e:"A competência comunicativa é a capacidade de comunicar eficazmente e adequadamente — saber o que dizer, como dizer, a quem, quando e em que contexto cultural e relacional."}
];

// ============================================================
// DATA: 50 FLASHCARDS
// ============================================================
const flashData = [
  {cat:"Glossário",t:"Comunicação Interpessoal",d:"Troca de informação, significado e emoções entre duas ou mais pessoas numa relação. É inseparável das relações humanas (Minter, 2010)."},
  {cat:"Glossário",t:"Sinais Não-Verbais",d:"Mensagens comunicadas sem palavras: gestos, expressões faciais, postura, toque, tom de voz e uso do espaço."},
  {cat:"Glossário",t:"TGIM — Teoria da Gestão da Informação Motivada",d:"Explica como as pessoas gerem a incerteza e ansiedade em situações de comunicação, procurando ou evitando informação."},
  {cat:"Glossário",t:"Teoria dos Objetivos Múltiplos",d:"Ao comunicar, perseguimos vários objetivos em simultâneo: instrumentais (obter algo), relacionais (manter a relação) e identitários (proteger a imagem)."},
  {cat:"Glossário",t:"Perfil Verbal-Não Verbal Discrepante",d:"Situação em que a mensagem verbal e a não-verbal são inconsistentes — o que se diz contradiz o que o corpo expressa."},
  {cat:"Glossário",t:"Troca Social",d:"Princípio de que as interações humanas envolvem trocas de recursos, custos e recompensas, orientadas pelo interesse próprio e reciprocidade."},
  {cat:"Glossário",t:"Interacionismo Simbólico",d:"Perspetiva que vê o comportamento social como resultado dos significados simbólicos que as pessoas constroem e partilham nas interações."},
  {cat:"Glossário",t:"Teorema de Thomas",d:"'Se as pessoas definem as situações como reais, elas são reais nas suas consequências' — o poder das perceções na comunicação."},
  {cat:"Glossário",t:"Escuta Ativa",d:"Forma de escuta em que o receptor demonstra atenção plena, compreensão e interesse ativo — fazendo perguntas, dando feedback, parafraseando."},
  {cat:"Glossário",t:"Escuta Empática",d:"Escuta que procura compreender os sentimentos e perspetiva emocional do outro, colocando-se no seu lugar sem julgamento."},
  {cat:"Glossário",t:"Escuta Reflexiva",d:"Técnica de escuta em que se reformula o que o outro disse — 'Então o que estás a dizer é...' — para confirmar compreensão."},
  {cat:"Glossário",t:"Barreiras Psicológicas",d:"Obstáculos à comunicação causados por preconceitos, emoções fortes, expectativas ou experiências passadas que distorcem a receção da mensagem."},
  {cat:"Glossário",t:"Barreiras Semânticas",d:"Interferências causadas por diferenças no significado atribuído às palavras ou símbolos entre emissor e recetor."},
  {cat:"Glossário",t:"Inteligência Emocional (IE)",d:"Capacidade de reconhecer, compreender e gerir as próprias emoções e as dos outros. Inclui: autoconsciência, autorregulação, motivação, empatia e competências sociais."},
  {cat:"Glossário",t:"IE de Habilidade (Ability)",d:"Conjunto de capacidades cognitivas: perceber, usar, compreender e regular emoções. Permite ler emoções nos outros com precisão."},
  {cat:"Glossário",t:"IE de Traço (Trait)",d:"Traços auto-reportados relacionados com autoeficácia emocional, bem-estar subjetivo e sociabilidade — como a pessoa percebe as suas características emocionais."},
  {cat:"Glossário",t:"IE Mista (Competências)",d:"Competências comportamentais observáveis: dar feedback, gerir conflitos, demonstrar empatia — aplicadas ao desempenho social e profissional."},
  {cat:"Glossário",t:"5 Pilares da IE (Goleman)",d:"Autoconsciência · Autorregulação · Motivação intrínseca · Empatia · Competências Sociais"},
  {cat:"Glossário",t:"Teoria da Atribuição",d:"Processo pelo qual interpretamos as causas do comportamento dos outros — atribuindo causas internas (personalidade) ou externas (situação)."},
  {cat:"Glossário",t:"Teoria da Troca Afetiva",d:"Explica como as emoções trocadas nas interações influenciam e regulam a qualidade das relações interpessoais."},
  {cat:"Glossário",t:"Estilo Assertivo",d:"'Eu venço, tu também venças.' Expressa necessidades com respeito pelos direitos próprios e alheios. Voz firme, contacto visual sem intimidar, expressão aberta."},
  {cat:"Glossário",t:"Estilo Passivo",d:"'Eu perco, tu ganhas.' Evita conflito, sublima necessidades, cede facilmente. Voz fraca, olhar desviado, hesitação constante."},
  {cat:"Glossário",t:"Estilo Agressivo",d:"'Eu venço, tu perdes.' Impõe necessidades atacando os outros. Ameaças, sarcasmo, olhar desafiante, gestos ameaçadores."},
  {cat:"Glossário",t:"Estilo Passivo-Agressivo",d:"Evita confronto direto mas manifesta insatisfação indiretamente: ironia, sabotagem velada, ambiguidades e resistência passiva."},
  {cat:"Glossário",t:"Modelo DESC",d:"Estrutura assertiva: Descreve o comportamento → Expressa sentimentos → Sugere mudança → Consequências positivas."},
  {cat:"Glossário",t:"Modelo XYZ",d:"'Quando fazes X, sinto Y, porque Z.' Expressa sentimentos sem acusar a pessoa, focando no comportamento específico."},
  {cat:"Glossário",t:"Teoria da Retórica Normativa (TRN)",d:"Combina os princípios clássicos de Aristóteles com ética comunicativa — como persuadir de forma eficaz, honesta e respeitosa."},
  {cat:"Glossário",t:"Ethos",d:"Credibilidade e integridade do comunicador. Pilar da persuasão: o público confia mais em quem percebe como competente e honesto."},
  {cat:"Glossário",t:"Logos",d:"Apelo à razão. Uso de argumentos lógicos, dados e evidências para convencer — o lado racional da persuasão."},
  {cat:"Glossário",t:"Pathos",d:"Apelo emocional. Ativar emoções do público (esperança, medo, empatia) para tornar a mensagem mais persuasiva — deve ser usado eticamente."},
  {cat:"Glossário",t:"Proxémica",d:"Estudo do uso do espaço físico nas interações. Zonas: íntima (~0-45cm), pessoal (~120cm), social (~360cm), pública (+360cm). (Hall)"},
  {cat:"Glossário",t:"Cinésica",d:"Estudo dos movimentos corporais como comunicação: gestos, postura, expressões faciais, contacto visual, orientação do corpo. (Birdwhistell)"},
  {cat:"Glossário",t:"Paralinguagem",d:"Elementos vocais que acompanham as palavras: tom, ritmo, volume, pausas, entonação, timbre — modificam o significado das mensagens."},
  {cat:"Glossário",t:"Metacomunicação",d:"Comunicar sobre o próprio processo de comunicação — 'Acho que não nos estamos a entender' é metacomunicação."},
  {cat:"Glossário",t:"Dissonância Cognitiva",d:"Desconforto psicológico causado por crenças contraditórias. Na comunicação, pode levar à rejeição de mensagens que contradizem crenças existentes."},
  {cat:"Glossário",t:"Janela de Johari",d:"Modelo com 4 quadrantes: Arena (conhecido por mim e outros), Ponto Cego (outros sabem, eu não), Fachada (eu sei, outros não), Desconhecido."},
  {cat:"Glossário",t:"Gestão de Impressões",d:"Processo pelo qual controlamos a informação que transmitimos para influenciar como somos percebidos pelos outros (Goffman)."},
  {cat:"Glossário",t:"Interdependência",d:"Nas relações, os resultados de cada pessoa são influenciados pelos esforços dos outros — o sucesso individual depende do parceiro."},
  {cat:"Glossário",t:"Reciprocidade",d:"Princípio de que as trocas nas relações devem ter retorno — quando alguém nos dá algo, sentimos necessidade de retribuir."},
  {cat:"Glossário",t:"Microexpressões",d:"Expressões faciais brevíssimas (menos de 0.5 segundos) que revelam emoções genuínas — difíceis de falsificar ou esconder."},
  {cat:"Glossário",t:"Competência Comunicativa",d:"Capacidade de comunicar de forma eficaz e adequada em diferentes contextos, relações e situações culturais."},
  {cat:"Glossário",t:"Comunicação Não-Violenta (CNV)",d:"Abordagem (Rosenberg): Observações → Sentimentos → Necessidades → Pedidos. Sem julgamentos ou críticas pessoais."},
  {cat:"Glossário",t:"Comunicação de Alto Contexto",d:"Estilo cultural onde muito do significado está no contexto implícito, nas relações e na comunicação não-verbal (ex: cultura japonesa)."},
  {cat:"Glossário",t:"Comunicação de Baixo Contexto",d:"Estilo cultural onde a mensagem é explícita e direta — a maioria do significado está nas palavras ditas (ex: cultura americana)."},
  {cat:"Glossário",t:"Princípio da Cooperação (Grice)",d:"Na comunicação eficaz, os interlocutores cooperam implicitamente: sendo informativos, verdadeiros, relevantes e claros (Máximas de Grice)."},
  {cat:"Glossário",t:"Ruído Semântico",d:"Interferência causada por diferenças no significado atribuído às palavras — mesmo com transmissão perfeita, há mal-entendido."},
  {cat:"Glossário",t:"Locus de Controlo Interno",d:"Crença de que controlamos os nossos resultados — associado a maior assertividade e eficácia comunicativa."},
  {cat:"Glossário",t:"Barreiras Tecnológicas",d:"Interferências na comunicação digital: falhas de ligação, ausência de sinais não-verbais, distrações de notificações, desumanização."},
  {cat:"Glossário",t:"Simbolismo",d:"No interacionismo simbólico, os símbolos (palavras, gestos, objetos) têm significados socialmente partilhados que medeiam todas as interações."},
  {cat:"Glossário",t:"Autenticidade Comunicativa",d:"Correspondência genuína entre o que se sente interiormente e o que se expressa — comunicar sem máscaras ou performatividade excessiva."}
];

// ============================================================
// DATA: 25 FILL IN THE BLANK
// ============================================================
const fitbData = [
  {s:"A comunicação interpessoal é, segundo Minter, quase sinónima de ___.", a:"relações humanas", alt:["relações", "relacionamentos"]},
  {s:"O estilo de comunicação considerado mais desejável é o ___.", a:"assertivo"},
  {s:"O ___ afirma que 'se as pessoas definem as situações como reais, elas são reais nas suas consequências'.", a:"Teorema de Thomas", alt:["teorema de thomas","thomas"]},
  {s:"Os 3 pilares da retórica de Aristóteles são Ethos, Logos e ___.", a:"Pathos", alt:["pathos"]},
  {s:"A capacidade de reconhecer e gerir as próprias emoções e as dos outros chama-se ___ ___.", a:"inteligência emocional", alt:["IE", "i.e."]},
  {s:"Na escuta ___, o receptor reformula o que o outro disse para confirmar compreensão.", a:"reflexiva"},
  {s:"O estilo ___ evita o conflito, sublima as necessidades e cede facilmente.", a:"passivo"},
  {s:"O estilo ___ impõe necessidades através de ameaças e ataques.", a:"agressivo"},
  {s:"O modelo ___ estrutura a comunicação assertiva: Descreve, Expressa, Sugere e Consequências.", a:"DESC"},
  {s:"O ___ é o apelo à credibilidade e integridade do comunicador na retórica.", a:"Ethos", alt:["ethos"]},
  {s:"O ___ é o apelo à razão e argumentos lógicos na retórica.", a:"Logos", alt:["logos"]},
  {s:"Na Troca Social, os custos e benefícios são flexíveis e baseados em ___.", a:"confiança"},
  {s:"O ___ afirma que o comportamento social resulta dos significados que atribuímos aos símbolos.", a:"Interacionismo Simbólico", alt:["interacionismo simbólico", "interacionismo"]},
  {s:"Os ___ são elementos fundamentais da comunicação: criam espaço para escutar o outro.", a:"silêncios", alt:["silencios"]},
  {s:"A ___ é o estudo do uso do espaço físico nas interações.", a:"proxémica", alt:["proxemica","proxemia"]},
  {s:"Quando a mensagem verbal e a não-verbal são contraditórias, temos um Perfil ___ Discrepante.", a:"Verbal-Não Verbal", alt:["verbal não verbal", "discrepante"]},
  {s:"Os 5 pilares da IE de Goleman incluem autoconsciência, autorregulação, motivação, empatia e ___.", a:"competências sociais", alt:["competencias sociais"]},
  {s:"A ___ é o estudo dos movimentos corporais como forma de comunicação.", a:"cinésica", alt:["cinesica","cinésica"]},
  {s:"A ___ é o estudo dos elementos vocais: tom, ritmo, volume, pausas e entonação.", a:"paralinguagem"},
  {s:"Comunicar sobre o próprio processo de comunicação chama-se ___.", a:"metacomunicação", alt:["metacomunicacao"]},
  {s:"O modelo ___ usa a estrutura 'Quando fazes X, sinto Y, porque Z'.", a:"XYZ"},
  {s:"A ___ na retórica normativa é o apelo emocional ao público.", a:"Pathos", alt:["pathos"]},
  {s:"A Teoria da Gestão da Informação ___ explica como gerimos incerteza e ansiedade ao comunicar.", a:"Motivada", alt:["motivada"]},
  {s:"Na comunicação de ___ contexto, o significado está principalmente nas palavras explícitas.", a:"baixo"},
  {s:"A Janela de ___ divide o autoconhecimento em Arena, Ponto Cego, Fachada e Desconhecido.", a:"Johari", alt:["johari"]}
];

// ============================================================
// DATA: STORY CHAPTERS
// ============================================================
const storyChapters = [
  {
    num:"Capítulo I", title:"O Mundo Antes das Palavras",
    body:`<p>Imagine que acordas num mundo sem linguagem. Nenhuma palavra, nenhuma frase — apenas corpos, olhares e gestos. Surpreendentemente, continuaríamos a <span class="concept">comunicar</span>. É este paradoxo que nos lembra da primeira grande verdade: <strong>a comunicação precede a língua</strong>.</p>
    <p>Segundo Minter (2010), a comunicação e as relações humanas são "quase sinónimas" — tão interligadas que estudar uma sem a outra é quase impossível. Para Watzlawick, os relacionamentos emergem da interação, regulada por regras que ambas as partes aceitam. E há uma regra universal: <span class="concept">é impossível não comunicar</span>.</p>
    <div class="highlight">"Os conceitos de comunicação e de relações humanas estão de tal modo relacionados que são quase sinónimos." — Minter, 2010</div>
    <p>Mas o que é, afinal, a <strong>Comunicação Interpessoal</strong>? É a troca de informação, significado e emoções entre pessoas — cara a cara, por voz, por texto, por um simples silêncio. É o mecanismo pelo qual construímos relações, identidades e sociedades inteiras.</p>
    <p>Antes de dizer uma palavra, já comunicamos: pela postura, pelo olhar, pelo espaço que escolhemos ocupar. É o reino da <span class="concept">comunicação não-verbal</span> — gestos, expressões faciais, toque, tom de voz. Estudos clássicos sugerem que mais de metade da nossa comunicação é não-verbal. O que diz o teu corpo quando as tuas palavras dizem o contrário?</p>`
  },
  {
    num:"Capítulo II", title:"Os Segredos do Silêncio e da Perceção",
    body:`<p>Dois alunos sentam-se lado a lado numa sala de aula. Um olha diretamente para o professor e acena com a cabeça. O outro olha para baixo e não diz nada. O professor pergunta-se: qual deles está a escutar? A resposta é: nenhum, necessariamente. <strong>Ouvir não é escutar.</strong></p>
    <p>Esta distinção está no coração da <span class="concept">Escuta Ativa</span>. Ouvir é passivo — a recepção de ondas sonoras. Escutar é ativo — implica processar, interpretar e responder. A <strong>Escuta Empática</strong> vai ainda mais longe: procura compreender a perspetiva emocional do outro, colocando-se no seu lugar. A <strong>Escuta Reflexiva</strong> fecha o ciclo, reformulando o que o outro disse.</p>
    <p>E os silêncios? São, paradoxalmente, comunicação. Criam espaço, transmitem emoções, marcam respeito. Para escutar o outro, precisamos primeiro de estar em silêncio.</p>
    <div class="highlight">O silêncio não é ausência de comunicação — é uma das suas formas mais poderosas.</div>
    <p>Mas a comunicação enfrenta barreiras constantes. <span class="concept">Barreiras psicológicas</span> — os nossos preconceitos e emoções — distorcem as mensagens. <span class="concept">Barreiras semânticas</span> criam ruído quando as mesmas palavras têm significados diferentes. <span class="concept">Barreiras tecnológicas</span> surgem quando o digital apaga os sinais não-verbais. E o <strong>Perfil Verbal-Não Verbal Discrepante</strong> aparece quando o que dizemos contradiz o que o corpo expressa — e o outro ouve sempre o corpo.</p>`
  },
  {
    num:"Capítulo III", title:"As Trocas que nos Unem",
    body:`<p>Todos os dias, sem perceber, fazemos centenas de cálculos. Quanto me custa esta conversa? O que ganho com ela? Vale a pena? Não é cinismo — é a <span class="concept">Teoria da Troca Social</span> em ação.</p>
    <p>A Troca Social é o princípio de que as interações humanas envolvem trocas de recursos, custos e recompensas. Ao contrário da troca económica — com preços fixos e contratos legais — a troca social é voluntária, baseada em confiança, com custos e benefícios flexíveis e negociados.</p>
    <p>O <strong>interesse próprio</strong> motiva as nossas ações — mas isso não significa egoísmo. Muitas vezes, <strong>cooperar</strong> é a estratégia mais racional, pois ambas as partes beneficiam. A <strong>equidade</strong>, a <strong>justiça</strong> e a <strong>reciprocidade</strong> afetam constantemente as nossas decisões sobre com quem e como interagimos.</p>
    <div class="highlight">A interdependência significa que os resultados de cada pessoa são influenciados pelos esforços dos outros.</div>
    <p>Mas as trocas vão além dos recursos tangíveis. O <span class="concept">Interacionismo Simbólico</span> revela que o que trocamos são sobretudo <strong>significados</strong> — símbolos carregados de interpretações culturais e pessoais. E o <strong>Teorema de Thomas</strong> lembra-nos: se definimos uma situação como real, ela torna-se real nas suas consequências. A realidade social é, em grande parte, construída pela perceção.</p>`
  },
  {
    num:"Capítulo IV", title:"A Tempestade Interior: Emoções e Inteligência",
    body:`<p>Imagina um líder de equipa que tem uma ideia brilhante mas não consegue que ninguém a ouça — porque cada palavra que diz provoca resistência. E imagina outro, com ideias medianas, que consegue mobilizar toda uma organização. A diferença? <span class="concept">Inteligência Emocional</span>.</p>
    <p>Goleman definiu a IE como a capacidade de reconhecer, compreender e gerir as próprias emoções e as dos outros. Os seus <strong>5 pilares</strong> são: autoconsciência, autorregulação, motivação intrínseca, empatia e competências sociais.</p>
    <p>Mas há três abordagens à IE. A <strong>IE de Habilidade</strong> vê-a como capacidade cognitiva: ler emoções com precisão, usá-las para pensar. A <strong>IE de Traço</strong> foca o autoconceito emocional: como eu me percebo emocionalmente. A <strong>IE Mista</strong> traduz-se em comportamentos: dar feedback, gerir conflitos, demonstrar empatia em ação.</p>
    <div class="highlight">A inteligência emocional ajuda-nos a interpretar as causas das emoções (atribuição) e a gerir as relações através das emoções que trocamos com os outros (troca afetiva).</div>
    <p>A <span class="concept">Teoria da Atribuição</span> explica como interpretamos o comportamento alheio — causas internas ("é preguiçoso") ou externas ("teve um dia difícil"). A <span class="concept">Teoria da Troca Afetiva</span> mostra que as emoções que circulam entre nós moldam a qualidade das nossas relações. Quem regula melhor as suas emoções, comunica melhor — e relaciona-se melhor.</p>`
  },
  {
    num:"Capítulo V", title:"A Arte de Ser Direto: Os Estilos de Comunicação",
    body:`<p>Três pessoas recebem a mesma crítica do chefe. A primeira responde: "Compreendo o seu ponto de vista. Na minha perspetiva, o projeto enfrenta os seguintes desafios..." — assertiva, clara, respeitosa. A segunda não diz nada, sorri forçado e vai para casa furiosa — passiva. A terceira explode: "Sempre a mesma conversa, nunca estão satisfeitos!" — agressiva.</p>
    <p>Estes são os três estilos clássicos de comunicação. O <span class="concept">Assertivo</span> — "eu venço, tu também venças" — defende os próprios direitos sem violar os dos outros. É firme, direto, respeitoso. O <span class="concept">Passivo</span> — "eu perco, tu ganhas" — evita conflito, sublima necessidades, cede sob pressão. O <span class="concept">Agressivo</span> — "eu venço, tu perdes" — impõe, ameaça, não coopera.</p>
    <p>Existe ainda o <strong>Passivo-Agressivo</strong>: evita o confronto direto mas manifesta insatisfação através de ironia subtil ou sabotagem velada — o mais difícil de gerir porque nunca é explícito.</p>
    <div class="highlight">A assertividade contribui para maior satisfação connosco próprios e com os outros, e melhora as relações. (Rego, 2016)</div>
    <p>Como comunicar assertivamente em situações difíceis? O <span class="concept">Modelo DESC</span> oferece uma estrutura: Descreve o comportamento → Expressa o que sentes → Sugere uma mudança → aponta as Consequências positivas. O <span class="concept">Modelo XYZ</span> simplifica: "Quando fazes X, sinto Y, porque Z" — foca no comportamento, não na pessoa.</p>`
  },
  {
    num:"Capítulo VI", title:"A Arte de Persuadir: Retórica e Ética",
    body:`<p>Há 2400 anos, Aristóteles sistematizou o que comunicadores intuitivos já sabiam: para persuadir, precisamos de credibilidade, lógica e emoção. A <span class="concept">Teoria da Retórica Normativa</span> combina estes princípios com a ética moderna.</p>
    <p>O <span class="concept">Ethos</span> é a credibilidade do comunicador — a perceção de integridade e competência que leva o público a confiar na mensagem. Sem Ethos, os outros dois pilares perdem força. O <span class="concept">Logos</span> é o apelo à razão — argumentos lógicos, dados, evidências. Convence o intelecto. O <span class="concept">Pathos</span> é o apelo emocional — ativar medo, esperança ou empatia para tornar a mensagem visceral.</p>
    <div class="highlight">A retórica normativa defende que o apelo emocional deve ser utilizado de forma ética, respeitando a capacidade do público de pensar criticamente.</div>
    <p>A distinção entre <strong>persuasão</strong> e <strong>manipulação</strong> é ética: a persuasão respeita a autonomia do outro; a manipulação explora vulnerabilidades. A TRN defende a persuasão ética — usar todos os pilares, mas nunca distorcer, exagerar ou explorar.</p>
    <p>Na prática, os melhores comunicadores integram os três pilares: são credíveis, fundamentam com evidências e sabem tocar o coração do público — sem nunca o enganar.</p>`
  },
  {
    num:"Capítulo VII", title:"O Futuro de Comunicar: Desafios Contemporâneos",
    body:`<p>Nunca estivemos tão ligados. E nunca a comunicação foi tão desafiante. A era digital trouxe velocidade, alcance e comodidade — mas também fragmentação, desumanização e a tentação da performance.</p>
    <p>A <span class="concept">autenticidade</span> tornou-se uma questão central: as redes sociais permitem construir personas cuidadosamente editadas, criando distância entre o "eu" apresentado e o "eu" real. A comunicação interpessoal genuína exige congruência — que o que expressamos corresponda ao que sentimos.</p>
    <p>A <strong>Cultura e o Contexto</strong> são dimensões que sempre moldaram a comunicação — e hoje, num mundo globalizado, são mais visíveis. Culturas de <span class="concept">alto contexto</span> (como a japonesa) comunicam muito implicitamente; culturas de <span class="concept">baixo contexto</span> (como a americana) são mais diretas. Compreender estas diferenças é essencial para comunicar eficazmente num mundo diverso.</p>
    <div class="highlight">A Comunicação adapta-se ao contexto e ao tempo em que vivemos. Nunca estivemos tão ligados, contudo, nem por isso estamos mais aptos a comunicar.</div>
    <p>O desafio do século XXI não é ter mais tecnologia — é ser mais humano dentro dela. Escutar com empatia num mundo de notificações. Ser assertivo num mundo de ecrãs. Comunicar com autenticidade num mundo de algoritmos. As ferramentas mudam; a natureza humana da comunicação permanece.</p>`
  }
];

// ============================================================
// DATA: GOSSIP MODE
// ============================================================
const gossipNarrative = [
  {type:"date", text:"Hoje, 09:12"},
  {type:"girl", who:"rita", text:"MENINAS acordem 🚨🚨🚨 tenho coisa GORDA", ts:"09:12"},
  {type:"girl", who:"mariana", text:"o que foi 😭😭", ts:"09:12"},
  {type:"girl", who:"beatriz", text:"estou em aula mas continua", ts:"09:13"},
  {type:"girl", who:"rita", text:"então vocês sabem a Ana Catarina certo? a do 3º ano que namorava com o Tiago que é amigo do primo da Sofia", ts:"09:13"},
  {type:"girl", who:"sofia", text:"ESPERA o Tiago do Surf Club???", ts:"09:13"},
  {type:"girl", who:"rita", text:"ESSE MESMO. então ontem à noite vejo ela no instagram a fazer story com outro tipo. mas tipo story normal nada demais. só que… o tipo estava de perfil e eu reconheci a casaco 💀", ts:"09:14"},
  {type:"girl", who:"mariana", text:"NÃO", ts:"09:14"},
  {type:"girl", who:"beatriz", text:"que casaco 😰", ts:"09:14"},
  {type:"girl", who:"rita", text:"o casaco VERDE do Tiago. aquele com o patch da banda. aquele que ele tem HÁ ANOS", ts:"09:14"},
  {type:"girl", who:"sofia", text:"ok mas pode ser coincidência não? casacos parecidos existem", ts:"09:15"},
  {type:"girl", who:"rita", text:"Sofia querida eu gosto de ti mas estás MUITO errada", ts:"09:15"},
  {type:"prof", theory:"Teoria da Atribuição", text:"<span class='theory-label'>📚 Teoria da Atribuição</span><br>Bom dia! Reparem neste momento — a Sofia fez uma <strong>atribuição externa</strong> (\"é coincidência\", causa na situação) enquanto a Rita fez uma <strong>atribuição interna</strong> (\"reconheci a casaco\", causa no comportamento da pessoa). A Teoria da Atribuição explica exatamente isto: como interpretamos as causas do comportamento dos outros muda completamente a nossa reação.", ts:"09:16"},
  {type:"girl", who:"beatriz", text:"prof com todo o respeito estamos a tentar perceber se a Ana Catarina está a trair o Tiago", ts:"09:16"},
  {type:"girl", who:"mariana", text:"💀💀💀 beatriz LMAO", ts:"09:16"},
  {type:"girl", who:"prof_skip", text:"ok continuem eu estou a ouvir 👀", ts:"09:17"},
  {type:"date", text:"09:18"},
  {type:"girl", who:"rita", text:"então eu decidi não dizer nada. tipo fiquei ali a ver o story. mas a minha amiga Inês que também os conhece viu e ficou tipo 'ah eu vi os dois juntos na biblioteca na semana passada mas achei que eram só amigos'", ts:"09:18"},
  {type:"girl", who:"sofia", text:"INÊS SABIA?? e não disse nada?!", ts:"09:19"},
  {type:"girl", who:"mariana", text:"ok isso é informação retida de propósito ou ela realmente não sabia o que estava a ver?", ts:"09:19"},
  {type:"girl", who:"rita", text:"É EXATAMENTE A PERGUNTA. porque eu falei com ela e ela disse que achou que eram só amigos. mas tipo… biblioteca a dois…", ts:"09:20"},
  {type:"prof", theory:"TGIM", text:"<span class='theory-label'>📚 TGIM — Gestão da Informação Motivada</span><br>Excelente exemplo! A Inês geriu a informação motivada pela redução de ansiedade — inconscientemente escolheu a interpretação menos perturbadora (\"são só amigos\") porque a alternativa causaria desconforto. A <strong>TGIM</strong> explica que gerimos ativamente quanto queremos saber e como interpretamos o que vemos, especialmente quando a verdade seria difícil de processar.", ts:"09:21"},
  {type:"girl", who:"beatriz", text:"okay mas prof e nós agora? também estamos a gerir informação motivada porque queremos saber TUDO 😭", ts:"09:21"},
  {type:"girl", who:"mariana", text:"ao contrário da Inês nós queremos a informação máxima AHAHAH", ts:"09:22"},
  {type:"date", text:"09:24"},
  {type:"girl", who:"rita", text:"ok PLOT TWIST. o Tiago viu o story. e em vez de reagir… não disse NADA. ficou em lido.", ts:"09:24"},
  {type:"girl", who:"sofia", text:"o silêncio é uma resposta por si próprio!!!", ts:"09:24"},
  {type:"girl", who:"beatriz", text:"Sofia acordaste hoje 👏", ts:"09:25"},
  {type:"girl", who:"sofia", text:"hm estudei ontem sobre comunicação não-verbal e silêncio como forma de comunicação… este prof está a entrar na minha cabeça", ts:"09:25"},
  {type:"prof", theory:"Comunicação Não-Verbal + Silêncio", text:"<span class='theory-label'>📚 Comunicação Não-Verbal & Silêncio</span><br>A Sofia acertou em cheio! O silêncio é um elemento fundamental da comunicação — não é ausência de mensagem, É a mensagem. Watzlawick diria que é <strong>impossível não comunicar</strong>: ao não responder, o Tiago comunicou algo (o quê exatamente, depende da interpretação de cada uma). Além disso, o <strong>Perfil Verbal-Não Verbal Discrepante</strong> aparece quando as ações (não reagir) contradizem o que seria esperado verbalmente.", ts:"09:26"},
  {type:"girl", who:"mariana", text:"prof isso significa que o Tiago sabe???", ts:"09:26"},
  {type:"girl", who:"rita", text:"OU significa que está a gerir a situação passivamente 👀", ts:"09:27"},
  {type:"date", text:"09:31"},
  {type:"girl", who:"beatriz", text:"ok eu investiguei. fui ao perfil do tipo do casaco. chama-se Rodrigo. e tem uma foto com a Ana Catarina de MARÇO. tipo quando eles ainda supostamente estavam juntos", ts:"09:31"},
  {type:"girl", who:"sofia", text:"MARÇO???", ts:"09:31"},
  {type:"girl", who:"mariana", text:"então isto não foi de repente. isto é uma NOVELA", ts:"09:32"},
  {type:"girl", who:"rita", text:"e agora vem a melhor parte. eu conheço a Ana Catarina razoavelmente bem. e ela tem um estilo de comunicação muito muito específico", ts:"09:32"},
  {type:"girl", who:"beatriz", text:"deixa adivinhar. nunca diz o que sente diretamente?", ts:"09:33"},
  {type:"girl", who:"rita", text:"JAMAIS. é sempre 'não é nada' e 'estou bem' mas com aquele tom que não está nada bem", ts:"09:33"},
  {type:"prof", theory:"Estilos de Comunicação", text:"<span class='theory-label'>📚 Estilos de Comunicação</span><br>Isto é um exemplo claro do estilo <strong>Passivo-Agressivo</strong>: evita o confronto direto mas manifesta insatisfação de forma indireta — através do tom, do silêncio estratégico, de ações veladas. É diferente do <strong>Passivo</strong> puro (que apenas suprime) — o passivo-agressivo age, mas nunca de forma direta. Comparem com o estilo <strong>Assertivo</strong>, que expressaria as necessidades com respeito: 'Não estou bem com esta situação porque...'", ts:"09:34"},
  {type:"girl", who:"mariana", text:"então ela nunca disse ao Tiago que estava insatisfeita?", ts:"09:35"},
  {type:"girl", who:"rita", text:"A Bruna que é amiga dela disse que ela ficou a acumular durante MESES. dizia que estava tudo bem. e depois um dia simplesmente desligou.", ts:"09:35"},
  {type:"girl", who:"sofia", text:"isso é tão triste. mas também tão previsível", ts:"09:36"},
  {type:"date", text:"09:40"},
  {type:"girl", who:"beatriz", text:"ok mas e o Tiago? alguém falou com ele?", ts:"09:40"},
  {type:"girl", who:"mariana", text:"o meu primo falou com ele ontem. e o Tiago está tipo em modo robô. responde a tudo com 'estou bem' e 'já passou' mas claramente NÃO passou", ts:"09:41"},
  {type:"girl", who:"rita", text:"o clássico do passivo puro 😔", ts:"09:41"},
  {type:"girl", who:"sofia", text:"ele está a escutar os amigos?", ts:"09:42"},
  {type:"girl", who:"mariana", text:"o meu primo disse que tentou falar com ele mas que ele muda de assunto constantemente", ts:"09:42"},
  {type:"prof", theory:"Escuta Ativa vs Ouvir", text:"<span class='theory-label'>📚 Escuta Ativa & Barreiras</span><br>O Tiago está a <strong>ouvir</strong> mas não a <strong>escutar</strong>. Ouvir é passivo — receber o som. Escutar implica processar, estar presente, responder genuinamente. As <strong>barreiras psicológicas</strong> — a dor emocional, o orgulho ferido — estão a impedir a escuta real. Além disso, os amigos podem estar a tentar aplicar <strong>Escuta Empática</strong> (entrar na perspetiva emocional dele) mas sem sucesso se ele não deixar espaço para isso.", ts:"09:43"},
  {type:"girl", who:"beatriz", text:"prof não devia estar a dar aula agora", ts:"09:43"},
  {type:"girl", who:"prof_skip", text:"tecnicamente estou. isto conta como estudo de caso 📋", ts:"09:44"},
  {type:"girl", who:"mariana", text:"AHAHAHA ACEITAMOS", ts:"09:44"},
  {type:"date", text:"09:48"},
  {type:"girl", who:"rita", text:"ok SEGUNDA VOLTA. a Bruna (amiga da Ana Catarina) postou agora mesmo uma foto com ela e o Rodrigo. com o caption 'os meus favoritos 🤍'", ts:"09:48"},
  {type:"girl", who:"sofia", text:"a Bruna sabia tudo desde o início???", ts:"09:48"},
  {type:"girl", who:"beatriz", text:"ou está a marcar território em nome da amiga lol", ts:"09:49"},
  {type:"girl", who:"mariana", text:"e agora toda a gente vai saber. é um comunicado oficial sem ser oficial", ts:"09:49"},
  {type:"prof", theory:"Gestão de Impressões + Simbólico", text:"<span class='theory-label'>📚 Gestão de Impressões & Interacionismo Simbólico</span><br>Fascinante! A Bruna usou dois mecanismos em simultâneo. Primeiro, <strong>Gestão de Impressões</strong> (Goffman): controlou deliberadamente a informação pública para influenciar como a Ana Catarina e o Rodrigo são percebidos — como casal legítimo. Segundo, <strong>Interacionismo Simbólico</strong>: aquela foto não é apenas uma foto — é um símbolo carregado de significado social: validação, oficialização, mensagem ao Tiago. O caption '🤍' é um símbolo que toda a gente lê de forma diferente conforme o que já sabe.", ts:"09:50"},
  {type:"girl", who:"rita", text:"PROF isso é exatamente o que aconteceu. toda a gente no grupo de amigos deles já está a comentar", ts:"09:51"},
  {type:"girl", who:"beatriz", text:"o drama da gestão de impressões fazer mais barulho do que o drama real", ts:"09:51"},
  {type:"date", text:"10:02"},
  {type:"girl", who:"sofia", text:"ok update: o Tiago viu a foto. e deixou um like.", ts:"10:02"},
  {type:"girl", who:"mariana", text:"UM LIKE??? que estilo de comunicação é esse prof??", ts:"10:02"},
  {type:"girl", who:"rita", text:"ou é assertividade forçada ou é o maior bluff da história", ts:"10:03"},
  {type:"prof", theory:"Objetivos Múltiplos", text:"<span class='theory-label'>📚 Teoria dos Objetivos Múltiplos</span><br>O like do Tiago é um exemplo perfeito de <strong>Objetivos Múltiplos em conflito</strong>. Ao mesmo tempo, ele quer: (1) proteger a sua imagem de que está bem (objetivo identitário), (2) não cortar completamente os laços sociais do grupo (objetivo relacional), e (3) talvez sinalizar que aceita a situação (objetivo instrumental). O like serve os três — é uma mensagem mínima que cobre o máximo de frentes. Comunicação altamente calculada, mesmo que pareça simples.", ts:"10:04"},
  {type:"girl", who:"beatriz", text:"um like a fazer trabalho de três objetivos em simultâneo... respeito honestamente", ts:"10:05"},
  {type:"girl", who:"mariana", text:"toda a teoria numa reação do instagram. este prof tem razão sobre tudo 😭", ts:"10:05"},
  {type:"date", text:"10:09"},
  {type:"girl", who:"rita", text:"ÚLTIMO UPDATE e juro que é o melhor. a Ana Catarina mandou mensagem ao Tiago. privada. e a Bruna mostrou à Inês que me mostrou a mim (com autorização ok não somos assim tão más)", ts:"10:09"},
  {type:"girl", who:"sofia", text:"O QUE DIZIA", ts:"10:09"},
  {type:"girl", who:"beatriz", text:"FALA RITA", ts:"10:10"},
  {type:"girl", who:"rita", text:"ela disse: 'espero que estejas bem. não quis que soubesses assim mas também nunca soube como dizer-te. desculpa.' E ele respondeu: 'obrigado por dizer. fica bem.'", ts:"10:10"},
  {type:"girl", who:"mariana", text:"…isso é bonito na verdade? tenho sentimentos contraditórios", ts:"10:11"},
  {type:"girl", who:"sofia", text:"ela foi assertiva no fim. finalmente.", ts:"10:11"},
  {type:"prof", theory:"Assertividade + DESC + Retórica", text:"<span class='theory-label'>📚 Assertividade, Modelo DESC & Ethos</span><br>A Ana Catarina finalmente usou comunicação <strong>assertiva</strong> — expressou os sentimentos com honestidade e sem atacar. Inconscientemente aplicou elementos do <strong>Modelo DESC</strong>: descreveu a situação ('não quis que soubesses assim'), expressou o sentimento ('nunca soube como dizer-te') e pediu desculpa. O Tiago respondeu com <strong>Ethos</strong> — credibilidade e dignidade — mantendo o tom respeitoso mesmo na dor. A mensagem dele é curta mas tem logos (racional), pathos (gentileza) e ethos (caráter). Às vezes as melhores comunicações são as mais simples.", ts:"10:12"},
  {type:"girl", who:"beatriz", text:"ok prof agora estou a chorar numa aula de cálculo obrigada", ts:"10:12"},
  {type:"girl", who:"rita", text:"AHAHAHA beatriz", ts:"10:13"},
  {type:"girl", who:"mariana", text:"resumo da manhã: aprendemos teoria da comunicação interpessoal E acompanhámos uma separação em tempo real", ts:"10:13"},
  {type:"girl", who:"sofia", text:"melhor aula do semestre sem dúvida", ts:"10:14"},
  {type:"prof", theory:"Fim", text:"<span class='theory-label'>📚 Nota Final</span><br>E com isto cobrimos: Teoria da Atribuição, TGIM, Comunicação Não-Verbal, Silêncio como Comunicação, Estilos (Passivo, Passivo-Agressivo, Assertivo), Escuta Ativa, Gestão de Impressões, Interacionismo Simbólico, Objetivos Múltiplos e Retórica (Ethos/Logos/Pathos). Boa sorte no exame. 📋", ts:"10:14"},
  {type:"girl", who:"rita", text:"vamos todos passar graças à Ana Catarina e ao Tiago 🙏", ts:"10:15"},
  {type:"girl", who:"mariana", text:"mandem-lhes bem", ts:"10:15"},
  {type:"girl", who:"beatriz", text:"🤍", ts:"10:15"},
  {type:"girl", who:"sofia", text:"🤍", ts:"10:15"}
];

// ============================================================
// DATA: 16 CENÁRIOS DE APLICAÇÃO (formato da prova escrita)
// ============================================================
const scenarioData = [
  {sc:"A Joana chega à reunião e diz com voz entusiasmada: 'Adoro esta ideia!' — mas está de braços cruzados, recostada para trás e a olhar para o telemóvel.",q:"Que conceito descreve melhor esta situação?",o:["Escuta reflexiva","Perfil Verbal-Não Verbal Discrepante","Comunicação de baixo contexto","Metacomunicação"],a:1,e:"As palavras (entusiasmo) contradizem os sinais não-verbais (postura fechada, distração) — é o Perfil Verbal-Não Verbal Discrepante. E o recetor tende a acreditar no corpo, não nas palavras."},
  {sc:"O Miguel suspeita que o colega de grupo não fez a parte dele do trabalho, mas decide não perguntar nada — 'prefiro nem saber, ainda fico mais ansioso'.",q:"Que teoria explica este comportamento?",o:["Teoria da Troca Afetiva","Teoria dos Objetivos Múltiplos","TGIM — Teoria da Gestão da Informação Motivada","Teorema de Thomas"],a:2,e:"A TGIM (Afifi & Weiner) explica que gerimos ativamente a procura de informação consoante a ansiedade: o Miguel evita informação para não aumentar o desconforto."},
  {sc:"A Carla quer pedir um aumento à chefe. Quer o aumento, mas também quer manter boa relação com ela e não quer parecer arrogante perante a equipa.",q:"Que teoria descreve os objetivos em jogo nesta conversa?",o:["Teoria dos Objetivos Múltiplos","Teoria da Atribuição","Interacionismo Simbólico","Teoria da Retórica Normativa"],a:0,e:"Há três objetivos simultâneos: instrumental (o aumento), relacional (a relação com a chefe) e identitário (a imagem perante a equipa) — o núcleo da Teoria dos Objetivos Múltiplos."},
  {sc:"O Rui acredita que toda a turma o acha aborrecido. Por isso, nas aulas nunca fala, evita os colegas e responde com frieza — e os colegas, sem o conhecer, acabam mesmo por se afastar.",q:"Que conceito explica o que aconteceu?",o:["Barreira semântica","Teorema de Thomas","Paralinguagem","Escuta empática"],a:1,e:"O Rui definiu a situação como real ('acham-me aborrecido') e ela tornou-se real nas consequências (afastamento). É exatamente o Teorema de Thomas — o poder das perceções."},
  {sc:"Numa discussão, a Inês diz ao namorado: 'Quando chegas atrasado sem avisar, sinto-me desvalorizada, porque parece que o meu tempo não conta.'",q:"Que modelo de comunicação assertiva está a Inês a usar?",o:["Modelo DESC","Modelo XYZ","Janela de Johari","Comunicação Não-Violenta de 4 passos"],a:1,e:"'Quando fazes X (chegas atrasado), sinto Y (desvalorizada), porque Z (o meu tempo não conta)' — é a estrutura exata do Modelo XYZ: foca o comportamento, não ataca a pessoa."},
  {sc:"O chefe do Pedro fala-lhe num tom seco: 'Preciso disto para ontem.' O Pedro pensa: 'Ele é mesmo mal-educado' — sem considerar que o chefe acabou de sair de uma reunião desastrosa.",q:"Que erro descreve melhor o raciocínio do Pedro?",o:["Atribuição interna ignorando causas externas (Teoria da Atribuição)","Dissonância cognitiva","Gestão de impressões","Ruído semântico"],a:0,e:"O Pedro atribuiu o comportamento a uma causa interna (personalidade: 'é mal-educado') ignorando a causa externa (a situação: reunião desastrosa) — o enviesamento clássico descrito pela Teoria da Atribuição."},
  {sc:"Numa apresentação, a oradora começa por referir os seus 15 anos de experiência na área, depois apresenta dados estatísticos sólidos e termina com a história emocionante de uma família afetada pelo problema.",q:"Que sequência de apelos retóricos foi usada?",o:["Pathos → Logos → Ethos","Ethos → Logos → Pathos","Logos → Ethos → Pathos","Ethos → Pathos → Logos"],a:1,e:"Experiência profissional = credibilidade (Ethos); dados estatísticos = razão (Logos); história emocionante = emoção (Pathos). A sequência clássica de Aristóteles."},
  {sc:"A Marta diz que está 'tudo ótimo' com a colega de casa, mas deixa a loiça suja de propósito, responde com ironia e 'esquece-se' de dar recados importantes.",q:"Que estilo de comunicação demonstra a Marta?",o:["Assertivo","Passivo","Agressivo","Passivo-agressivo"],a:3,e:"Evita o confronto direto ('tudo ótimo') mas expressa a insatisfação por vias indiretas (sabotagem velada, ironia) — a definição de passivo-agressivo."},
  {sc:"Durante uma conversa difícil, o psicólogo responde: 'Se bem percebo, o que me estás a dizer é que te sentes posto de lado quando o teu irmão recebe mais atenção. É isso?'",q:"Que tipo de escuta está a ser usado?",o:["Escuta reflexiva","Escuta passiva","Escuta seletiva","Audição ativa"],a:0,e:"Reformular o que o outro disse para confirmar compreensão ('se bem percebo... é isso?') é a marca da Escuta Reflexiva."},
  {sc:"Numa empresa multinacional, o gestor português envia instruções diretas e detalhadas por escrito. O parceiro japonês considera-o frio e desrespeitoso; o português acha o japonês evasivo, porque 'nunca diz claramente o que quer'.",q:"Que conceito explica este desencontro?",o:["Barreiras tecnológicas","Comunicação de alto contexto vs. baixo contexto","Perfil Verbal-Não Verbal Discrepante","Locus de controlo"],a:1,e:"A cultura japonesa (alto contexto) comunica pelo implícito e pela relação; a portuguesa/ocidental (mais baixo contexto) privilegia a mensagem explícita. O choque entre os dois estilos gera as perceções negativas mútuas."},
  {sc:"O André partilha no Instagram apenas fotos no ginásio, em viagens e com roupa cara — apesar de passar a maioria dos dias em casa a jogar. Quer que os antigos colegas o vejam como bem-sucedido.",q:"Que conceito de Goffman está aqui presente?",o:["Janela de Johari","Gestão de impressões","Troca social","Autenticidade comunicativa"],a:1,e:"O André controla deliberadamente a informação que transmite para influenciar como é percebido — Gestão de Impressões (Goffman). (E nota o conflito com a autenticidade comunicativa.)"},
  {sc:"A Sara ajudou a Rita na mudança de casa. Meses depois, a Sara precisa de boleia para o aeroporto e fica genuinamente magoada quando a Rita recusa sem justificação.",q:"Que princípio da Troca Social foi violado?",o:["Interdependência","Equidade salarial","Reciprocidade","Maximização de resultados"],a:2,e:"Quando damos algo, criamos expectativa de retorno — reciprocidade. A recusa da Rita quebra essa expectativa implícita, gerando a mágoa da Sara."},
  {sc:"Num debate aceso, o Tomás repara que está a ficar furioso. Respira fundo, identifica a emoção ('estou irritado porque me sinto ignorado') e decide adiar a resposta para não dizer algo de que se arrependa.",q:"Que pilares da IE de Goleman estão a ser mobilizados?",o:["Empatia e competências sociais","Autoconsciência e autorregulação","Motivação e empatia","Apenas competências sociais"],a:1,e:"Reconhecer a própria emoção no momento = autoconsciência; gerir o impulso e adiar a resposta = autorregulação. Os dois primeiros pilares de Goleman."},
  {sc:"A professora explica 'avaliação contínua' à turma. Para ela significa trabalhos ao longo do semestre; vários alunos entendem que basta ir às aulas. No fim do semestre, há surpresas desagradáveis.",q:"Que barreira à comunicação ocorreu?",o:["Barreira fisiológica","Barreira semântica","Barreira tecnológica","Barreira ambiental"],a:1,e:"Emissor e recetores atribuíram significados diferentes à mesma expressão ('avaliação contínua') — uma barreira semântica clássica, mesmo com transmissão perfeita."},
  {sc:"O Vasco diz à equipa: 'Acho que não me estou a explicar bem — deixem-me tentar de outra forma. O que é que perceberam até agora?'",q:"O que está o Vasco a fazer?",o:["Metacomunicação e pedido de feedback","Escuta empática","Persuasão por Pathos","Atribuição externa"],a:0,e:"Comunicar sobre a própria comunicação ('não me estou a explicar bem') é metacomunicação; perguntar o que perceberam é pedir feedback para fechar o ciclo comunicativo."},
  {sc:"Numa entrevista de emprego, a candidata mantém contacto visual tranquilo, voz firme e calma, e responde: 'Discordo dessa abordagem e explico porquê — mas compreendo o raciocínio por trás dela.'",q:"Que estilo de comunicação e que componente não-verbal estão alinhados?",o:["Agressivo, com postura dominante","Assertivo, com sinais não-verbais congruentes","Passivo, com sinais discrepantes","Passivo-agressivo, com ironia"],a:1,e:"Defende a posição com respeito ('discordo... mas compreendo') = assertividade; contacto visual sem intimidar e voz firme e calma são os sinais não-verbais congruentes do estilo assertivo."}
];
